label chapter_2_osis:
    "{cps=35}Seperti biasa, [y] sudah menunggu di depan rumah{/cps}"
    y "{cps=35}Selamat pagi, [mc]{/cps}"
    mc "{cps=35}Selamat pagi...{/cps}"
    "{cps=35}[y] memperhatikanku dengan sangat jeli{/cps}"
    y "{cps=35}Hah... gini ya [mc]...{/cps}"
    y "{cps=35}Masa pagi-pagi sudah lemas?{/cps}"
    y "{cps=35}Mana dasimu masih berantakan lagi!{/cps}"
    "{cps=35}[y] langsung menarik dasiku{/cps}"
    mc "{cps=35}UWA!? Apa yan-{/cps}"
    y "{cps=35}Masa aku harus merapihkannya setiap hari sih?{/cps}"
    y "{cps=35}Memang sih kita tetangga, tapi ya nggak gini juga{/cps}"
    mc "{cps=35}Diamlah{/cps}"
    y "{cps=35}Tuh kan, dibilangin malah gini{/cps}"
    mc "{cps=35}Kalau kamu tidak mau merapihkan tidak usah ngomel{/cps}"
    "{cps=35}Aku langsung menjauh dari [y]{/cps}"
    y "{cps=35}Hei! Aku belum selesai tahu!{/cps}"
    mc "{cps=35}Kamu sendiri kan yang ingin kita bergegas?{/cps}"
    y "{cps=35}Memang sih... tapi kan-{/cps}"
    mc "{cps=35}Sudahlah, kita jalan sekarang{/cps}"
    y "{cps=35}Cih! Dasar...{/cps}"
    y "{cps=35}Tunggu aku!{/cps}"
    "{cps=35}Kami pun berjalan menuju sekolah{/cps}"
    "{cps=35}Sepanjang jalan, [y] tidak berhenti mengoceh tentang jadwal OSIS yang dia dapatkan dari grup pesan singkat semalam. Energinya benar-benar tidak ada habisnya.{/cps}"
    if jajan:
        y "{cps=60}Oh iya, [mc]! Kemarin kamu kan habis traktir aku dan Vina. Nanti di kantin aku traktir balik ya!{/cps}"
        mc "{cps=40}Ah, nggak usah.{/cps}"
        y "{cps=60}Harus! Masa aku mau berhutang terus? Lagipula sekarang kita satu organisasi, wajar saling support.{/cps}"
        mc "{cps=35}Aku kurang yakin tentang itu...{/cps}"
        y "{cps=35}Kamu ngatain aku ya?{/cps}"
        mc "{cps=35}Nggak kok...{/cps}"
        
    else:
        y "{cps=60}Ngomong-ngomong.. kamu nggak menyesal kan pilih OSIS? Soalnya kemarin aku lihat kamu agak... bimbang?{/cps}"
        mc "{cps=40}Enggak. Ini pilihanku sendiri.{/cps}"
        y "{cps=60}Syukurlah kalau begitu. Kita jalanin bareng-bareng ya!{/cps}"
        mc "{cps=35}Iya [y]..{/cps}"
    
    y "{cps=35}Oh iya!{/cps}"
    y "{cps=35}Katanya hari ini kita bakal dibagi ke beberapa divisi. Aku berharap kita satu divisi, biar seru!{/cps}"
    mc "{cps=35}Divisi? padahal anggota total cuman 8?{/cps}"
    mc "{cps=35}Itu sudah termasuk angkatan kita loh{/cps}"
    y "{cps=35}Ya... siapa tahu ada anggota tambahan{/cps}"
    mc "{cps=35}Terserah kamu lah [y]{/cps}"
    mc "{cps=35}Toh yang menentukan pada akhirnya ya ketua{/cps}"
    y "{cps=35}Iya sih, tapi kalau kita bareng kan asik{/cps}"
    "{cps=35}Kalau dipikir memang sih aku sama [y] sudah ada koneksi{/cps}"
    mc "{cps=35}Tapi kemungkinan besar aku akan membuat dia kerepotan{/cps}"
    mc "{cps=35}Nanti kamu nyusahin aku lagi{/cps}"
    y "{cps=35}Bukannya kebalik ya?{/cps}"
    mc "{cps=35}Adududuh... apa sih{/cps}"
    "{cps=35}[y] mencubit pipiku{/cps}"

    "???" "{cps=35}Aduh.. pagi-pagi sudah mesra aja, [mc]{/cps}"
    y "{cps=35}Ah, [yk]! Selamat pagi!{/cps}"
    yk "{cps=35}Otsu!{/cps}"
    "{cps=35}Di belakang [yk], terlihat [sh] yang hanya memandang kami dengan wajah yang datar{/cps}"
    y "{cps=35}Nee-san, ucapkan salam juga dong{/cps}"
    sh "{cps=35}Pagi{/cps}"
    mc "{cps=35}Pagi...{/cps}"
    "{cps=35}[sh] langsung meninggalkan adiknya yang sedang berbicara dengan kami{/cps}"
    yk "{cps=35}Ah! Tunggu....{/cps}"
    yk "{cps=35}Maaf ya, Nee-san sedang badmood hari ini{/cps}"
    y "{cps=35}Sebaiknya kamu langung menyusulnya deh{/cps}"
    yk "{cps=35}Itu sudah pasti, sampai jumpa di kelas, [mc], [y]!{/cps}"
    "{cps=35}[yk] langsung mengejar [sh]{/cps}"
    "{cps=35}Dan mereka langsung berbincang di depan kami{/cps}"
    y "{cps=35}[sh] kenapa ya...{/cps}"
    y "{cps=35}Kamu tau sesuatu, [mc]?{/cps}"
    mc "{cps=35}Entahlah...{/cps}"
    "{cps=35}Padahal aku tahu banget.. Aku yang salah{/cps}"
    "{cps=35}Sebaiknya aku berbincang dengannya{/cps}"
    y "{cps=35}Hei... [y] ke [mc]...{/cps}"
    mc "{cps=35}Ah!{/cps}"
    y "{cps=35}Kamu tidak memikirkan hal aneh kan?{/cps}"
    mc "{cps=35}Ummn.... nggak kok{/cps}"
    y "{cps=35}Mencurigakan... nanti aku bahas sama [v]{/cps}"
    mc "{cps=35}Terserah dirimu saja, [y]{/cps}"

    scene bg_classroom_morning with fade
    "{cps=35}Kami tiba di kelas tepat saat bel masuk berbunyi. Syukurlah, [t] belum datang.{/cps}"

    if jajan:
        "{cps=35}Aku duduk di bangku, masih memikirkan janji Yuuka soal traktiran. Mungkin hari ini dompetku bisa selamat.{/cps}"
    elif ciduk:
        "{cps=35}Aku duduk di bangku, mencoba melupakan kejadian kemarin saat hampir tertangkap kak Maya. Setidaknya sekarang aku sudah resmi di OSIS.{/cps}"
    else:
        "{cps=35}Aku duduk di bangku, merasa sedikit bersalah karena tidak ikut ke kantin kemarin. Tapi setidaknya Yuuka tidak marah.{/cps}"

    "{cps=35}Vina yang duduk di belakangku langsung menyenggol kursiku.{/cps}"

    show vina_smile with dissolve
    v "{cps=60}Hei, Specimen! Dengar-dengar kalian bertemu keluarga Shirohana di gerbang tadi?{/cps}"
    mc "{cps=40}Kamu tahu dari mana?{/cps}"
    v "{cps=60}Fufufu, di sekolah ini tidak ada yang bisa disembunyikan dari Vina~{/cps}"
    
    if guess_correct:
        v "{cps=60}Katanya kamu bisa bedain Shoko dan Yukie dari belakang? Hebat juga.{/cps}"
    else:
        v "{cps=60}Katanya kamu sempat salah panggil? Duh, malu-maluin.{/cps}"

    mc "{cps=35}Sebentar...{/cps}"
    mc "{cps=35}Perasaan kamu dari kemarin selalu tahu apa yang aku lakukan{/cps}"
    mc "{cps=35}Kamu penguntit ya?{/cps}"
    v "{cps=35}Hah? Nggak kok{/cps}"
    mc "{cps=35}Dari rawut wajahmu tidak meyakinkan, [v]{/cps}"
    v "{cps=35}Cuman perasaanmu saja kok [mc]{/cps}"
    v "{cps=35}Koneksiku memang banyak{/cps}"
    v "{cps=35}Ditambah kan kamu cuman satu-satunya anak laki disini{/cps}"
    v "{cps=35}Jadi ya yang menguntit dirimu banyak{/cps}"
    mc "{cps=35}Ah! Tidak mungkin itu{/cps}"
    mc "{cps=35}Masa pria sepertiku diuntit banyak orang{/cps}"
    v "{cps=35}Kamu belum menyadarinya, [mc]{/cps}"
    v "{cps=35}Tapi ada yang benar-benar melakukannya{/cps}"
    v "{cps=35}Namun karena itu sangat rahasia jadi tidak akan aku beritahu kepadamu{/cps}"
    v "{cps=35}Lagipula kamu kan tidak peduli{/cps}"
    mc "{cps=35}Nanti kamu jelasin pas istirahat{/cps}"
    v "{cps=35}Kalau aku ingat...{/cps}"
    "{cps=35}Bel tanda dimulainya jam pertama sudah berbunyi{/cps}"

    "{cps=40}Disaat aku melamun....{/cps}"
    "{cps=40}BRAK!{/cps}"
    mc"{cps=40}Hue! Apa yan-{/cps}"
    "{cps=40}[t] melempar buku ke mejaku dengan cukup keras{/cps}"
    t "{cps=40}Hah.... gini ya [mc]{/cps}"
    t "{cps=40}Meskipun kamu sedang ngantuk...{/cps}"
    t "{cps=40}{b}MINIMAL MEMPERHATIKAN!{/b}{/cps}"
    mc "{cps=50}Baik bu...{/cps}"
    "{cps=50}Sial... {w=0.1}kenapa jadi begini...{/cps}"
    "{cps=50}Terdengar suara [v] yang tertawa kecil di belakangku. Dia pasti menikmati pemandangan ini.{/cps}"

    t "{cps=40}Karena kamu sepertinya punya dunia sendiri di dalam kepala itu, coba selesaikan soal yang ada di papan.{/cps}"
    
    t "{cps=40}Jika 3x + 5 = 20, berapakah nilai dari x?{/cps}"

    "{cps=35}Aduh... kepalaku mendadak kosong. Angka-angka itu seolah menari-nari di depan mataku.{/cps}"
    "{cps=35}Yuuka di depanku terlihat panik, dia mengangkat lima jarinya di bawah meja sebagai isyarat.{/cps}"
    "{cps=40}Aku harus menjawab apa...{/cps}"
    menu:
        "5":
            $ correct_answer = True
            $ yuuka_rel += 5
            $ vina_rel += 5
            mc "{cps=40}Jawabannya... 5, Bu.{/cps}"
            
            "{cps=35}Ibu [t] terdiam sejenak, lalu menurunkan kacamatanya.{/cps}"
            
            t "{cps=40}Tepat. Sederhana, bukan?{/cps}"
            t "{cps=40}Ingat, dalam Aljabar, tujuan kita adalah mencari 'Nilai yang Hilang' (x) dengan cara menyeimbangkan kedua sisi.{/cps}"
            
            "{cps=35}Ibu [t] menuliskan coretan di papan dengan cepat.{/cps}"
            t "{cps=40}Jika kamu punya masalah besar (20) dan ada gangguan kecil (+5), hilangkan gangguannya dulu (20-5). Baru kemudian bagi beban sisa (15) dengan kapasitasmu (3).{/cps}"
            
            "{cps=35}Entah kenapa, penjelasan Bu [t] barusan tidak hanya terdengar seperti matematika, tapi seperti cara menghadapi hidup yang sedang berantakan ini.{/cps}"
            t "{cps=35}Sudah paham?{/cps}"
            mc "{cps=35}Sudah bu?{/cps}"
            t "{cps=40}Lain kali, perhatikan penjelasan saya. Duduk dan fokus!{/cps}"
            t "{cps=35}Sekarang kembali ke tempat dudukmu{/cps}"
            mc "{cps=35}Ba-baik bu{/cps}"
            
            show yuuka_smile with dissolve
            "{cps=35}Yuuka menghela napas lega dan tersenyum kecil ke arahku. Di belakang, Vina tampak sedikit kecewa karena tidak bisa menertawakanku.{/cps}"
            v "{cps=60}Cih... ternyata si Specimen Langka ini bisa berhitung juga.{/cps}"

        "15":
            $ correct_answer = False
            $ yuuka_rel -= 2
            mc "{cps=40}Jawabannya... 15, Bu?{/cps}"
            
            "{cps=35}Seketika seisi kelas tertawa. Bahkan Vina di belakangku sampai harus menutup mulutnya agar tidak terdengar terlalu keras.{/cps}"
            t "{cps=40}Lima belas? Kamu ini sedang menghitung nilai x atau harga gorengan di kantin? Salah!{/cps}"
            t "{cps=40}Berdiri di depan sampai jam pelajaran saya selesai!{/cps}"
            
            show yuuka_sad with dissolve
            "{cps=35}Yuuka menepuk jidatnya. Dia sudah memberiku kode, tapi aku malah salah tangkap.{/cps}"

        "3":
            $ correct_answer = False
            $ yuuka_rel -= 2
            mc "{cps=40}Jawabannya... 3?{/cps}"
            
            t "{cps=40}Salah! Ternyata lamunanmu benar-benar merusak kemampuan logikamu.{/cps}"
            t "{cps=40}Silakan berdiri di samping papan tulis sampai saya selesai menjelaskan.{/cps}"
            
            "{cps=35}Aku hanya bisa tertunduk lesu sementara beberapa siswi lain berbisik-bisik menertawakanku.{/cps}"

    "{cps=50}Kelas pun kembali dilanjutkan{/cps}"
    if correct_answer:
        "{cps=35}Untung saja tadi jawabanku benar...{/cps}"
    else:
        "{cps=35}Andai saja tadi jawabanku benar... mungkin kakiku tidak akan sepegal ini karena berdiri di depan.{/cps}"
    
    "{cps=40}Dan tidak terasa sudah waktunya istirahat.{/cps}"
    
    play sound "audio/school_bell.mp3"
    t "{cps=40}Baiklah, karena waktunya sudah jam segini, silakan kalian istirahat.{/cps}"
    t "{cps=40}Nanti kita ketemu lagi di jam siang.{/cps}"
    
    "Satu Kelas" "{cps=40}Baik, Bu!{/cps}"
    "{cps=40}[t] langsung meninggalkan kelas.{/cps}"

    mc "{cps=40}Hah.... akhirnya.{/cps}"
    
    if correct_answer == False:
        "{cps=40}[v] dan [y] langsung menghampiriku.{/cps}"
        "{cps=40}Sepertinya mereka ingin memberiku semacam 'wejangan'.{/cps}"
        
        show yuuka_determined at left
        show vina_smile at right
        with dissolve

        v "{cps=40}Yo! {w=0.1}Anak bodoh.{/cps}"
        mc "{cps=40}Hei!{/cps}"
        v "{cps=40}Ayolah, aku cuman bercanda. Tapi serius, ekspresimu tadi lucu sekali.{/cps}"
        mc "{cps=40}Apa sih...{/cps}"
        v "{cps=40}Tapi kakimu gimana? {w=0.1} Sehat?{/cps}"
        mc "{cps=40}Saking sehatnya aku sampai malas jalan{/cps}"
        v "{cps=40}Ahaha, sudah ku duga{/cps}"
        y "{cps=40}Padahal sudah aku beritahu kodenya, [mc]. Kenapa kamu malah melamun?{/cps}"
        mc "{cps=40}Maaf... kepalaku mendadak blur melihat angka-angka itu.{/cps}"
        y "{cps=40}Kamu ini kebiasaan{/cps}"
        v "{cps=40}Heee kode apa tuch?{/cps}"
        y "{cps=40}Bukan apa-apa{/cps}"
        "{cps=40}[y] langsung pergi meninggalkanku{/cps}"
        v "{cps=40}Lah? Kenapa malah pergi{/cps}"
        v "{cps=40}[y].....{/cps}"
        "{cps=40}[v] langung mengejar [y]{/cps}"
        "{cps=40}Meninggalkanku sendiri{/cps}"
            
    else:
        "{cps=40}[v] dan [y] langsung menghampiriku.{/cps}"
        "{cps=40}Sepertinya mereka ingin memberiku semacam 'wejangan'.{/cps}"
        
        show yuuka_determined at left
        show vina_smile at right
        with dissolve

        v "{cps=40}Yo! {w=0.1}Anak pintar{/cps}"
        mc "{cps=40}Aku hanya beruntung tadi{/cps}"
        v "{cps=40}Sayang sekali tidak ada drama...{/cps}"
        v "{cps=40}Padahal kan aku ingin melihatmu kena hukuman{/cps}"
        mc "{cps=40}Hei! Niatmu buruk sekali ya.{/cps}"
        y "{cps=40}Syukurlah kamu bisa menjawabnya, [mc]. Aku sempat panik tadi.{/cps}"
        y "{cps=40}Lain kali jangan melamun lagi, ya?{/cps}"
        mc "{cps=40}Iya, maaf...{/cps}"
        v "{cps=40}Tapi ya sudahlah. Setidaknya hari ini aman, kan?{/cps}"
        mc "{cps=40}Aman sih...{/cps}"
        v "{cps=40}Mau ke kantin?{/cps}"
        if jajan == True:
            mc "{cps=40}Nggak terima kasih, aku masih kenyang.{/cps}"
            "{cps=40}(Karena tidak ingin keluar duit aja sih...){/cps}"
        else:
            mc "{cps=40}Sepertinya nggak dulu deh Vin, aku masih kenyang.{/cps}"
        
        v "{cps=40}Hah... yaudah kalau begitu.{/cps}"
        v "{cps=40}Ayo Ka, kita ke kantin!{/cps}"
        y "{cps=40}Ayo.{/cps}"

        "{cps=40}Mereka pun pergi meninggalkanku sendiri.{/cps}"
        "{cps=40}...{/cps}"

    "{cps=40}Suasana tenang ini{/cps}"
    "{cps=40}Kapan ya terakhir kali aku merasakannya...{/cps}"
    "{cps=35}Di tengah suasana yang hening ini{/cps}"
    "{cps=35}Tiba-tiba ada yang memanggilku{/cps}"
    yk "{cps=35}Yo, [mc]{/cps}"
    mc "{cps=35}Ah! [yk], ada apa?{/cps}"
    yk "{cps=35}Kamu daritadi melamun terus, sedang mikirin apa?{/cps}"
    mc "{cps=35}Nggak mikirin hal aneh kok{/cps}"
    yk "{cps=35}Lantas kenapa kamu nggak ikut mereka ke kantin?{/cps}"
    if correct_answer == False:
        mc "{cps=35}Aku ditinggalin mereka{/cps}"
        yk "{cps=35}Hah? Seorang [mc] ditinggal?{/cps}"
        mc "{cps=35}Kenapa kamu sampai kaget begitu?{/cps}"
        yk "{cps=35}Yaa... soalnya kan kalian biasa bareng{/cps}"
        mc "{cps=35}Kan kamu ngeliatnya kemarin{/cps}"
        yk "{cps=35}Memang sih{/cps}"
    else:
        mc "{cps=35}Aku lagi nggak ingin ikut mereka kok{/cps}"
        yk "{cps=35}Masa? Padahal kamu kelihatan akrab dengan mereka{/cps}"
        mc "{cps=35}Itu dari pandanganmu aja kali{/cps}"
    
    mc "{cps=35}Ditambah aku juga tidak membawa uang yang banyak{/cps}"
    yk "{cps=35}Berapa yang kamu bawa?{/cps}"
    mc "{cps=35}200 yen{/cps}"
    yk "{cps=35}Dikit!{/cps}"
    mc "{cps=35}Jangan mengina dong!{/cps}"
    yk "{cps=35}Nggak menghina sih... lebih tepatnya kasihan{/cps}"
    mc "{cps=35}Aku tidak perlu dikasihani{/cps}"
    yk "{cps=35}Aku tidak kasihan kepadamu, tapi perutmu...{/cps}"
    "{cps=35}*krunyuk....{/cps}"
    mc "{cps=35}Ah... ketahuan ya?{/cps}"
    yk "{cps=35}Ayo ikut aku{/cps}"
    mc "{cps=35}Ngapain?{/cps}"
    yk "{cps=35}Mending kamu tanya ke orang yang tahu jawabannya{/cps}"
    mc "{cps=35}Memangnya siapa yang tahu?{/cps}"
    yk "{cps=35}Coba aja cek kelas ini{/cps}"
    "{cps=35}Aku memandang sekeliling kelas, mencari yang sekiranya tahu jawabannya{/cps}"
    mc "{cps=35}Hmmm...{/cps}"
    "{cps=35}Aku merasa ada dua orang yang memandangku{/cps}"
    "{cps=35}Yang satu aku tahu dia siapa{/cps}"
    "{cps=35}Namun yang satunya, aku tidak kenal{/cps}"
    "{cps=35}Dia memandangku dari depan pintu{/cps}"
    "{cps=35}Sampai mata kami bertatapan secara tidak sengaja{/cps}"
    mc "{cps=35}Ah!{/cps}"
    "???" "{cps=35}Hue-{/cps}"
    "{cps=35}Dia langsung pergi{/cps}"
    "{cps=35}Siapa sih gadis itu...{/cps}"
    yk "{cps=35}Hei... jawabanmu?{/cps}"
    mc "{cps=35}Oh iya! Aku hampir lupa{/cps}"
    mc "{cps=35}Aku ikut{/cps}"
    yk "{cps=35}Oke kalau begitu... [sh]-nee{/cps}"
    "{cps=35}Ada apa?{/cps}"
    yk "{cps=35}Ayo kita makan bersama!{/cps}"
    "{cps=35}Memangnya makanan kita cukup untuk bertiga?{/cps}"
    yk "{cps=35}Loh, bukannya tadi pagi kakak masak lebih banyak?{/cps}"
    "{cps=35}Hah?{/cps}"
    yk "{cps=35}Sudahlah, ayo kita makan{/cps}"
    mc "{cps=35}Makan dimana memangnya? Kalau dikelas kan terlalu ramai{/cps}"
    yk "{cps=35}Aman kalau itu{/cps}"
    yk "{cps=35}Ikuti aku{/cps}"
    mc "{cps=35}U-uh..{/cps}"
    "{cps=35}Aku dan [sh] mengikuti [yk]. Berbeda dengan [y] yang langkahnya selalu terburu-buru{/cps}"
    "{cps=35}[yk] melangkah dengan sangat ringan, seolah dia sedang menari di atas lantai koridor ini.{/cps}"
    "{cps=35}Tentu saja, [sh] berada disampingnya{/cps}"
    yk "{cps=35}Sip, disini tempatnya{/cps}"
    "{cps=35}Kami sampai di sebuah pintu di ujung koridor yang sepi. Papan namanya tertulis 'Klub Sastra'.{/cps}"
    mc "{cps=35}Hei... ini kan ruangan klub kalian{/cps}"
    yk "{cps=35}Lantas?{/cps}"
    mc "{cps=35}Ya... kan aku bukan anggota{/cps}"
    yk "{cps=35}Tapi kan kamu kelaparan{/cps}"
    yk "{cps=35}Tidak mungkin kami membiarkan orang kelaparan{/cps}"
    yk "{cps=35}Kamu juga berpikiran gitu kan, [sh]-nee?{/cps}"
    sh "{cps=35}Benar [yk]{/cps}"
    if correct_answer == False:
        yk "{cps=35}Tadi kamu menjawab pertanyaan aja salah, pasti karena belum makan bukan?{/cps}"
    else:
        yk "{cps=35}Tadi saja suara perutmu sudah kedengeran{/cps}"
    mc "{cps=35}Ugh... memang sih{/cps}"
    yk "{cps=35}Tidak apa-apa kok, [mc]{/cps}"
    yk "{cps=35}Kan kami yang mengajakmu{/cps}"
    mc "{cps=35}Umm... kan bukannya hanya kamu yang mengajakku?{/cps}"
    "{cps=35}[yk] hanya menyeringai nakal, lalu dia menoleh ke arah kakaknya yang sedang memegang gagang pintu.{/cps}"
    yk "{cps=35}Menurut [sh]-nee?{/cps}"
    sh "{cps=35}Tidak masalah{/cps}"
    "{cps=35}Jawaban [sh] singkat, tapi cukup untuk membuatku masuk ke dalam.{/cps}"

    play sound "audio/door_slide.mp3"
    scene bg_lit_club_room with dissolve

    yk "{cps=35}Okay... menu hari ini apa kak?{/cps}"
    sh "{cps=35}Seperti biasa, sandwich{/cps}"
    yk "{cps=35}Woah... kelihatannya sangat lezat{/cps}"
    yk "{cps=35}Selamat makan!{/cps}"
    "{cps=35}Menu makanan siang ini memang biasa saja{/cps}"
    "{cps=35}Namun kehangatan yang ada di ruangan ini... membuatku merasa nyaman{/cps}"
    yk "{cps=35}[mc], kenapa kamu tidak memakannya?{/cps}"
    mc "{cps=35}Ah.... nggak kenapa-kenapa kok{/cps}"
    mc "{cps=35}Hanya saja aku teringat situasi di masa lalu{/cps}"
    "{cps=35}[sh] yang mendengar ucapanku langsung terdiam{/cps}"
    sh "{cps=35}Ingatan...{/cps}"
    mc "{cps=35}hm?{/cps}"
    sh "{cps=35}Kamu sudah ingat?{/cps}"
    mc "{cps=35}Beda hal sih, bukan denganmu{/cps}"
    sh "{cps=35}Oh..{/cps}"
    "{cps=35}[sh] langsung menunduk, seakan-akan aku mengucapkan hal yang sangat menjengkelkan{/cps}"
    sh "{cps=35}Berarti masih belum ya..{/cps}"
    yk "{cps=35}Tidak apa-apa lah, nee-san{/cps}"
    sh "{cps=35}Sedikit demi sedikit{/cps}"
    sh "{cps=35}Pasti kamu akan mengingat semua kenangan kita, [mc]{/cps}"
    mc "{cps=35}Semoga saja...{/cps}"
    "{cps=35}Kami makan dalam diam yang nyaman.{/cps}"
    "{cps=35}Tapi saat gigitan pertama menyentuh lidahku...{/cps}"
    "{cps=35}Kilatan ingatan yang samar muncul di kepalaku{/cps}"
    scene bg_event_flashback with vpunch
    stop music fadeout 1.0

    "{cps=35}Seorang gadis kecil berambut merah duduk di sampingku...{/cps}"
    "{cps=35}Dia menyodorkan potongan sandwich yang pinggirannya sudah dipotong rapi.{/cps}"
    
    "gadis kecil" "{cps=30}[mc], ayo makan... nanti mama kamu marah loh{/cps}"
    
    "{cps=35}Aku tidak bisa melihat wajahnya, tapi suaranya... terdengar begitu tulus.{/cps}"
    yk "{cps=35}Heii... [mc]{/cps}"
    scene bg_lit_club_room with flash
    mc "{cps=35}Hah!?{/cps}"
    yk "{cps=35}Kamu tidak apa-apa kan?{/cps}"
    yk "{cps=35}Kamu terlihat aneh sejak aku ajak...{/cps}"
    mc "{cps=35}Umn..{/cps}"
    "{cps=35}[sh] tiba-tiba berdiri dari kursinya{/cps}"
    "{cps=35}Dan langsung menyentuh dahiku{/cps}"
    sh "{cps=35}Dari suhunya... tidak masalah{/cps}"
    sh "{cps=35}Namun kamu terlihat sedang banyak pikiran{/cps}"
    mc "{cps=35}Sepertinya begitu...{/cps}"
    sh "{cps=35}Kalau memang ada yang mengganjal, ceritakan saja.{/cps}"
    sh "{cps=35}Jangan ditahan{/cps}"
    mc "{cps=35}Mungkin... tapi belum waktunya{/cps}"
    sh "{cps=35}Sebaiknya kamu jangan memaksakan diri{/cps}"
    mc "{cps=35}Iya...{/cps}"
    "{cps=35}Makan siang berakhir dengan keheningan yang canggung{/cps}"
    mc "{cps=35}Aku ke kelas duluan ya!{/cps}"
    yk "{cps=35}Okey, sampai nanti!{/cps}"
    "{cps=35}[sh] hanya mengangguk mendengar perkataanku{/cps}"
    "{cps=35}Aku langsung meninggalkan ruangan klub itu dan langsung berjalan kembali menuju kelas.{/cps}"
    "{cps=35}Dan pas sampai pertigaan lorong{/cps}"
    v "{cps=35}Well well well...{/cps}"
    if correct_answer == True:
        v "{cps=35}Kamu katanya kenyang{/cps}"
        v "{cps=35}Tapi kok kamu malah berkeliaran?{/cps}"
    else:
        "{cps=35}Kamu ngapain jam segini ada dilorong?{/cps}"
        "{cps=35}Padahal kan udah mau masuk?{/cps}"

    mc "{cps=35}Bukan urusanmu kan, [v]{/cps}"
    v "{cps=35}Loh kok gitu?{/cps}"
    v "{cps=35}Kamu pasti habis melakukan sesuatu kan?{/cps}"
    mc "{cps=35}Aku hanya dari kamar mandi, nggak lebih{/cps}"
    v "{cps=35}Tapi perutmu lebih berisi?{/cps}"
    v "{cps=35}Kamu tidak bisa menutupinya dariku loh, meski kamu mau berbohong seperti apapun{/cps}"
    "{cps=35}[v] mendekatiku secara tiba-tiba{/cps}"
    v "{cps=35}Ditambah dari bau mulutmu itu, ada rasa manis yang tak terdefinisikan{/cps}"
    "{cps=35}Ugh... aku sepertinya tidak bisa membohonginya{/cps}"
    mc "{cps=35}Ya, aku habis makan{/cps}"
    v "{cps=35}Nah, gitu dong jujur{/cps}"
    v "{cps=35}Makan dimana?{/cps}"
    mc "{cps=35}Di klub sastra{/cps}"
    v "{cps=35}Hah?{/cps}"
    v "{cps=35}Ngapain kamu di klub sastra?{/cps}"
    mc "{cps=35}aku diajak [yk]{/cps}"
    v "{cps=35}Heee.... lalu kamu setuju aja gitu?{/cps}"
    mc "{cps=35}Ya aku kan lapar, ditambah ga ada ongkos juga{/cps}"
    mc "{cps=35}Itupun akibat kalian yang kemarin aku jajanin{/cps}"
    v "{cps=35}Ah! kamu masih rada kesal ya?{/cps}"
    "{cps=35}Nggak sih{/cps}"
    v "{cps=35}Yang bener...{/cps}"
    "{cps=35}Dibilang nggak{/cps}"
    v "{cps=35}Tuh kan kesal{/cps}"
    "{cps=35}Sebaiknya aku langsung meninggalkan [v]{/cps}"
    "{cps=35}Daripada aku diintrogasi lagi{/cps}"
    mc "{cps=35}Maaf Vin, aku ada keperluan lain{/cps}"
    v "{cps=35}Eh!? Tung-{/cps}"
    "{cps=35}Aku langsung berlari meninggalkan dia{/cps}"
    v "{cps=35}Hah... sepertinya aku terlalu menggodanya{/cps}"
    v "{cps=35}Namun sebaiknya aku kasih tahu [y]{/cps}"
    "{cps=35}Sementara itu...{/cps}"
    mc "{cps=35}Fyuh... sepertinya [v] tidak mengejarku{/cps}"
    mc "{cps=35}Aku harap dia tidak menceritakan itu semua ke [y]{/cps}"
    y "{cps=35}Menceritakan tentang apa [mc]?{/cps}"
    mc "{cps=35}Loh? Sejak kapan kamu disini!?{/cps}"
    y "{cps=35}Ummnn.... {w=0.1} sejak kamu lari menuju pojokan{/cps}"
    y "{cps=35}Ceritalah [mc], aku kan penasaran{/cps}"
    mc "{cps=35}Meski aku cerita ke kamu, kamu ga bakal mengerti{/cps}"
    y "{cps=35}Ayolah, kenapa sih kamu menghindar?{/cps}"
    y "{cps=35}Padahal kan kita 1 organisasi{/cps}"
    mc "{cps=35}Bukan begitu [y], hanya saja...{/cps}"
    y "{cps=35}Hanya?{/cps}"
    y "{cps=35}Cepatlah kamu cerita, biar semuanya clear{/cps}"
    y "{cps=35}Kalau kayak gini kan aku ga tau ceritanya gimana{/cps}"
    mc "{cps=35}Kamu tidak akan kesal kan?{/cps}"
    y "{cps=35}Selagi kamu ngomong jujur ya nggak{/cps}"
    "{cps=35}Ga mungkin sih itu{/cps}"
    "{cps=35}Aku kan kenal [y] ga cuman 1 - 2 tahun aja{/cps}"
    mc "{cps=35}umn....{/cps}"
    menu:
        "Kasih tau":
            $ tell_yuuka = True
            $ yuuka_rel += 3
            mc "{cps=60}Baiklah kalau itu maumu{/cps}"
            mc "{cps=35}Aku habis makan di tempat klub sastra{/cps}"
            y "{cps=35}Heee... siapa yang ngajak?{/cps}"
            mc "{cps=35}[yk]{/cps}"
            y "{cps=35}Kok aku ga diajak?{/cps}"
            mc "{cps=35}Kamu aja tadi ga bareng aku{/cps}"
            mc "{cps=35}Kalo bareng mah tadi dapet sandwich{/cps}"
            y "{cps=35}Cih{/cps}"
            y "{cps=35}Enak ya...{/cps}"
            mc "{cps=35}Terus, ada apa lagi?{/cps}"
            y "{cps=35}Ummmmm.....{/cps}"

        "Tidak perlu":
            $ tell_yuuka = False
            $ yuuka_rel -= 3
            mc "{cps=35}Sepertinya kamu ga usah bertanya deh [y]{/cps}"
            y "{cps=35}Kamu kok selalu gitu sih belakangan ini{/cps}"
            y "{cps=35}Padahal sebelum sekolah disini kamu nggak gitu{/cps}"
            y "{cps=35}Ditambah sekarang kita 1 organisasi{/cps}"
            mc "{cps=35}Memangnya kalau aku cerita kamu mau apa?{/cps}"
            y "{cps=35}Ya apa salahnya kalau aku tahu{/cps}"
            mc "{cps=35}Padahal tidak menarik{/cps}"
            y "{cps=35}Nggak mungkin itu tidak menarik{/cps}"
            y "{cps=35}Aku kan selalu menunggu ceritamu{/cps}"
            mc "{cps=35}Hah... nanti aku cerita deh{/cps}"
            y "{cps=35}Ingat ya, wajib cerita pas pulang!{/cps}"
            mc "{cps=35}Iya, terus apa lagi?{/cps}"
            y "{cps=35}Ummm....{/cps}"


    y "{cps=35}Kamu kok nggak ke kelas?{/cps}"
    mc "{cps=35}Ya... tadi aku mau ke kelas dihalangin sama [v]{/cps}"
    y "{cps=35}Hah.. kebiasaan{/cps}"
    y "{cps=35}Nanti aku bilangin dia{/cps}"
    y "{cps=35}Ayo kita ke kelas, [mc]{/cps}"
    mc "{cps=35}Hm!{/cps}"
    "{cps=35}Kami langsung menuju ke kelas kami{/cps}"
    "{cps=35}Tentu saja selama dijalan [y] selalu membicarakan segala hal{/cps}"
    v "{cps=35}Yo, [mc]!{/cps}"
    "{cps=35}Apa?{/cps}"
    "{cps=35}Ayolah, ga perlu se kaku itu{/cps}"
    "{cps=35}Kamu mau ngapain?{/cps}"
    "{cps=35}Kamu nanya itu apa karena dapat teguran dari [y]{/cps}"
    "{cps=35}Ah! Ketahuan ya?{/cps}"
    "{cps=35}Pake nanya{/cps}"
    "{cps=35}Ya begitulah{/cps}"
    "{cps=35}Dasar tukang ngadu{/cps}"
    "{cps=35}Daripada kamu, tukang kompor{/cps}"
    "{cps=35}Perasaan aku tidak bawa kompor ke sekolah{/cps}"
    "{cps=35}Sudahlah vin, lelah aku berbicara denganmu{/cps}"
    "{cps=35}Yee...{/cps}"
    "{cps=35}Ah sial, sudah bel{/cps}"
    "{cps=35}[v] langsung kembali ke tempat duduknya{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"
    "{cps=35}{/cps}"