label chapter_2_solo:
    scene bg_classroom with fade
    play music "audio/bgm/schoolgate.mp3" fadein 2.0

    "{cps=35}Aku melangkah masuk ke kelas dengan napas yang masih sedikit memburu. Suasana kelas pagi ini terasa sangat bising, tipikal kelas yang ditinggal gurunya.{/cps}"

    "{cps=35}Aku melihat Yuuka sudah duduk di bangkunya. Dia sedang dikerumuni oleh beberapa siswi lain, tapi matanya sesekali melirik ke arah pintu.{/cps}"

    if jujur == False:
        "{cps=35}Saat mata kami bertemu, Yuuka langsung membuang muka dan pura-pura tertawa mendengar cerita teman di sebelahnya.{/cps}"
        "{cps=35}Hatiku mencelos. Sepertinya hari ini akan menjadi hari yang sangat panjang.{/cps}"
    else:
        "{cps=35}Yuuka melambai pelan ke arahku, meski senyumnya tidak selebar biasanya. Setidaknya, dia masih mau menatapku.{/cps}"

    "{cps=35}Aku berjalan menuju bangkuku. Namun, sebelum aku sempat duduk, seseorang menepuk bahuku dari belakang.{/cps}"

    "{cps=50}Dan seperti yang kuduga{/cps}"

    "{cps=40}[v] muncul di belakangku dengan wajah yang sedikit curiga{/cps}"

    show vina_smile with dissolve
    v "{cps=60}Yo! [mc]. Wajahmu seperti orang yang baru saja lolos dari pengadilan akhirat, memangnya ada apa?{/cps}"

    mc "{cps=40}Kamu ini selalu muncul tiba-tiba ya, [v].{/cps}"

    v "{cps=60}Fufufu, nggak juga kok. Oh iya, kemarin [m]-senpai membawamu pergi ke mana?.{/cps}"
    v "{cps=60}Apakah dia membuangmu ke gudang belakang, atau kamu berhasil melakukan 'negosiasi' dengannya?{/cps}"
    
    # TAMBAHAN START
    "{cps=35}Vina menumpukan dagunya di atas tangannya yang terlipat di sandaran kursiku. Matanya yang tajam seolah sedang memindai setiap inci reaksiku.{/cps}"
    
    mc "{cps=40}Negosiasi? Apa maksudmu?{/cps}"
    
    v "{cps=60}Ayolah [mc], coba ceritakan. Dia pasti menyebutkan nama 'Ikazaki [mi]', kan?{/cps}"
    "{cps=35}Loh? Kok dia tahu terkait kakakku?{/cps}"
    v "{cps=35}Hm? Kenapa wajahmu berubah jadi sepucat kertas begitu?{/cps}"
    
    mc "{cps=40}Kamu... nguping?{/cps}"
    
    v "{cps=60}Ya... anggap saja aku punya 'telinga' di mana-mana... lagipula sekolah ini punya dinding yang cukup tipis untuk telinga yang terlatih{/cps}"
    "{cps=35}Jadi, apa pilihanmu?{/cps}"
    # TAMBAHAN END
    mc "{cps=40}Aku... {w=0.1}tidak masuk ke organisasi manapun.{/cps}"
    mc "{cps=40}Aku baru saja menyerahkan kertasnya pada [m]-senpai tadi di gerbang.{/cps}"
    if jujur == False:
        "[y] dan [v]" "{cps=35}HAH!?{/cps}"
        "{cps=35}Terdengar suara kursi yang terjatuh dari depanku{/cps}"
        "{cps=35}Kemudian [y] datang menghampiriku{/cps}"
    else:
        "{cps=35}Terdengar suara kursi di depanku{/cps}"
        "{cps=35}Kemudian [y] datang menghampiriku{/cps}"
        "{cps=35}Sepertinya pembicaraan intens akan dimulai...{/cps}"
    y "{cps=35}Kamu serius tidak gabung ke organisasi manapun?{/cps}"
    mc "{cps=35}Yap, aku sudah menetapkan pilihanku{/cps}"
    "{cps=35}Beneran nih?{/cps}"
    mc "{cps=35}Masa iya aku bohong{/cps}"
    if jujur == False:
        mc "{cps=35}Maaf ya aku telat memberitahumu, [y]...{/cps}"
        "{cps=35}Karena aku tahu, jika aku memberitahumu dari awal, pasti kamu tidak terima{/cps}"
    else:
        mc "{cps=35}Kalian tidak keberatan kan?{/cps}"
    v "{cps=35}Gimana ya... dibilang keberatan sih nggak{/cps}"
    v "{cps=35}Namun... kalau kamu gabung ke osis pasti suasananya semakin asik!{/cps}"
    v "{cps=35}Kamu setuju kan [y]?{/cps}"
    y "{cps=35}Benar tuh! Kenapa kamu nggak gabung ke osis aja sih [mc]?{/cps}"
    v "{cps=35}Padahal kakakmu juga dari osis juga kan?{/cps}"
    "{cps=35}*BRAK{/cps}"
    mc "{cps=35}Kamu jangan pernah membawa kakakku ke dalam topik pembicaraan ini{/cps}"
    v "{cps=35}Hue- apa sih?{/cps}"
    "{cps=35}Aku... mau ke kamar mandi dahulu{/cps}"
    "{cps=35}Aku berdiri, meninggalkan mereka berdua di kelas itu{/cps}"
    v "{cps=35}Apaan sih dia itu?{/cps}"
    v "{cps=35}Padahal kan aku hanya ingin mengajaknya gabung{/cps}"
    y "{cps=35}Nggak gitu caranya [v]!{/cps}"
    v "{cps=35}Lantas?{/cps}"
    y "{cps=35}Kalau kita mengungkit kakaknya, dia pasti gitu{/cps}"
    y "{cps=35}Dari SMP pun begitu...{/cps}"
    "{cps=35}Suasana lorong yang dingin sedikit mendinginkan kepalaku. Aku bersandar di dinding, menatap ujung sepatuku yang sudah mulai kusam.{/cps}"
    "{cps=40}Sial... Kenapa aku harus semarah itu? Vina hanya... dia hanya tidak tahu apa-apa.{/cps}"
    "{cps=35}Aku berhenti di depan jendela besar yang menghadap ke halaman depan. Aku mengepalkan tangan, mencoba menahan emosi yang meluap.{/cps}"
    "???" "{cps=35}Kamu ngapain berdiri di situ?{/cps}"
    mc "{cps=35}Hah?{/cps}"
    "{cps=35}Aku tersentak. Di ujung koridor, bersandar di tembok, seorang gadis yang sangat familiar...{/cps}"
    mc "{cps=40}Kamu... siapa?{/cps}"
    "???" "{cps=35}HAH? Kamu serius nggak kenal aku?{/cps}"
    mc "{cps=35}Sebentar... coba aku ingat-ingat...{/cps}"
    "{cps=35}Siapa ya namanya?{/cps}"
    menu:
        "Kisaragi [f]":
            $ tebak = True
            $ fumi_rel += 5
            mc "{cps=40}Kak [f]?{/cps}"
            f "{cps=35}Benar sekali!{/cps}"
            f "{cps=35}Ternyata kamu punya ingatan yang bagus ya?{/cps}"
            mc "{cps=35}Nggak juga..{/cps}"
            f "{cps=35}Ah! gini saja{/cps}"
            f "{cps=35}Akan aku lakukan perkenalan ulang{/cps}"

        "Pembawa acara saat penyambutan?":
            $ tebak = False
            mc "{cps=40}Kakak pembawa acara saat penerimaan?{/cps}"
            "???" "{cps=40}Ya... nggak salah sih...{/cps}"
            "???" "{cps=40}Tapi masa kamu tidak tahu namaku{/cps}"
            "???" "{cps=40}Padahal aku perkenalan loh waktu itu{/cps}"
            mc "{cps=40}Maaf kak aku tidak terlalu ingat...{/cps}"
            "???" "{cps=40}Cih! yaudah, aku ulangi lagi{/cps}"

    f "{cps=35}Namaku adalah Kisaragi [f], pembawa acara penerimaan kemarin dan juga ketua klub sastra{/cps}"
    f "{cps=35}Namamu ikazaki [mc] kan?{/cps}"
    "{cps=35}Kenapa dia tahu namaku?{/cps}"
    mc "{cps=35}I-iya kak, kenapa?{/cps}"
    f "{cps=35}Kamu kenapa keluyuran di lorong? Padahal sekarang kan sudah mau jam pertama...{/cps}"
    mc "{cps=35}Entahlah kak.. aku merasa telah melakukan banyak hal buruk...{/cps}"
    f "{cps=35}Heee... memangnya apa saja?{/cps}"
    mc "{cps=35}Memangnya aku perlu menceritakan semua?{/cps}"
    f "{cps=35}Ceritain garis besarnya nggak apa-apa sih, lagipula kan sepertinya kamu perlu teman curhat{/cps}"
    mc "{cps=40}Hah... aku lelah, Kak. Semua orang menatapku seolah aku adalah replika dari kakakku yang sudah tiada.{/cps}"

    mc "{cps=40}Mereka ingin aku masuk OSIS, mereka ingin aku menjadi 'hebat' seperti dia. Tapi saat aku menolak, aku justru dianggap sebagai pengecut yang melarikan diri.{/cps}"

    f "{cps=35}Berdiri di bawah bayangan pohon yang besar memang sejuk, tapi kamu tidak akan pernah mendapatkan sinar matahari untuk dirimu sendiri, kan?{/cps}"

    "{cps=35}Aku terdiam. Kalimat itu... rasanya terlalu tepat sasaran.{/cps}"

    "{cps=35}Fumi menatapku dengan tatapan yang sangat tenang. Tidak ada rasa kasihan di matanya, hanya sebuah pemahaman yang mendalam.{/cps}"
    f "{cps=35}Aku mengerti perasaanmu, [mc]...{/cps}"
    "{cps=35}Kakak memangnya tahu apa?{/cps}"
    "{cps=35}Di nama keluargaku ada nama Kisaragi kan?, dan di sekolah ini, nama itu punya 'beban' tersendiri karena kakakku.{/cps}"
    mc "{cps=40}Iya kak, memangnya kenapa?{/cps}"
    f "{cps=40}Kamu tahu idol yang terkenal, Kisaragi [sa]?{/cps}"

    mc "{cps=40}Aku tahu kak, kalau tidak salah dia itu berada di satu era dengan Ogata [ri] dan Morikawa [yu] kan?{/cps}"
    f "{cps=35}Benar sekali{/cps}"
    mc "{cps=35}Lantas?{/cps}"
    f "{cps=35}Aku adalah adiknya{/cps}"
    mc "{cps=35}Hah? {w=0.1} Yang bemar kak?{/cps}"
    f "{cps=35}Kalau kamu berpikir aku hanya membual tidak masalah, nanti kamu ketika istirahat coba ke ruang klub sastra{/cps}"
    f "{cps=35}Akan aku ceritakan semua{/cps}"
    mc "{cps=35}Ummm....{/cps}"
    f "{cps=35}Sampai nanti{/cps}"
    mc "{cps=35}Tunggu ka-{/cps}"
    "{cps=35}[f] pergi tanpa meninggalkan jejak{/cps}"
    mc "{cps=35}Kak...{/cps}"

    "{cps=35}*TENG TENG TENG{/cps}"
    "{cps=35}Bunyi bell jam pertama sudah berbunyi{/cps}"
    mc "{cps=35}Sial.. kenapa jadi menggantung gini...{/cps}"
    "{cps=35}Aku harus bertemu dengannya nanti{/cps}"

    scene bg_classroom with fade
    play music "audio/bgm/tiptoeing around.mp3" fadein 2.0

    "{cps=35}Langkah kakiku terasa berat saat memasuki kelas. Suara gesekan kursi dan gumaman murid-murid lain seolah menjadi hakim atas kepergianku yang tiba-tiba tadi.{/cps}"

    "{cps=35}Aku duduk di kursiku tanpa berani melirik ke arah Yuuka. Aku bisa merasakan tatapannya yang tajam dari samping, tapi aku memilih untuk menatap lurus ke papan tulis yang masih kosong.{/cps}"

    v "{cps=60}(Berbisik pelan dari belakang) Wah, si Specimen sudah kembali. Wajahmu terlihat lebih... 'penuh rahasia' daripada sepuluh menit yang lalu.{/cps}"

    mc "{cps=40}(Berbisik) Diamlah, Vin.{/cps}"

    "{cps=35}Suasana kelas yang biasanya bising kini terasa mencekam. Meskipun murid-murid lain mulai kembali berbisik, ada dinding tak kasat mata yang terbangun di sekeliling mejaku, meja Yuuka, dan meja Vina.{/cps}"

    "{cps=35}Aku hanya bisa menatap nanar ke arah papan tulis yang masih bersih. Di kepalaku, kalimat Fumi terus berputar: 'Adik dari Kisaragi Sayoko'. Bagaimana mungkin seorang idol itu punya hubungan darah dengan seniorku?{/cps}"

    play sound "audio/sfx/sliding door.mp3"
    "{cps=35}*SRAAAK!*{/cps}"

    "{cps=35}[t] melangkah masuk dengan aura yang sanggup membekukan seisi ruangan. Beliau tidak membawa tas, hanya setumpuk buku tebal dan sebatang kapur yang digenggam kuat.{/cps}"
    t "{cps=40}Selamat pagi anak-anak, sekarang letakkan smartphone kalian, kita akan segera memulai pelajaran{/cps}"

    t "{cps=35}Sekarang kita akan mempelajari mata pelajaran yang cukup sulit, jadi saya harap kalian bisa fokus mengikuti pelajarannya{/cps}"
    "murid" "{cps=35}Baik bu{/cps}"
    "{cps=35}Beliau melirik ke arahku sejenak. Tatapannya tajam, seolah beliau tahu aku baru saja membuat keributan di lorong.{/cps}"
    t "{cps=35}Terutama kamu, [mc]{/cps}"
    mc "{cps=35}Lah kok saya bu?{/cps}"
    t "{cps=40}Karena wajahmu terlihat lagi banyak pikiran, [mc]. Apa pikiranmu sedang tertinggal di suatu tempat di luar sana?{/cps}"
    mc "{cps=35}Eh? N-nggak kok, Bu...{/cps}"
    t "{cps=35}Kalau begitu usahakan kamu untuk tetap fokus mengikuti pelajaran hari ini{/cps}"
    mc "{cps=35}Baik bu!{/cps}"
    "{cps=35}Kelas pun dilanjutkan dengan suasana yang sedikit canggung{/cps}"
    "{cps=35}Walau aku masih bisa mengikuti materinya sih{/cps}"
    "{cps=35}Namun entah kenapa... {w=0.1} Kalimat yang diucapkan oleh kak [f] masih nyangkut di pikiranku{/cps}"
    mc "{cps=35}'Nanti kamu ketika istirahat coba ke ruang klub sastra, akan aku ceritakan semua' ya...{/cps}"
    "{cps=35}Aku bergumam memikirkan itu{/cps}"
    "{cps=35}Memangnya apa sih yang akan dia ceritakan{/cps}"
    "{cps=35}Palingan juga cerita terkait keluarganya yang lengkap itu{/cps}"
    "{cps=35}Ditambah dia adalah pembawa acara kemarin... sudah pasti dia itu terlatih{/cps}"
    "{cps=35}Dibandingkan diriku yang saat ini saja melakukan apa-apa sendiri dan tidak memiliki koneksi yang cukup..{/cps}"
    "{cps=35}Itu bukan jalan yang cocok{/cps}"
    "{cps=35}Kalimat yang diucapkan [mom] kembali mengganggu pikiranku{/cps}"
    "{cps=35}'Kamu harus jadi orang sukses!'{/cps}"
    "{cps=35}Dikira gampang apa mah...{w=0.1} minimal perhatikan dahulu kualitas anakmu ini...{/cps}"
    "{cps=35}Memang sih dimana-mana itu banyak orang tua yang mengharapkan anaknya itu lebih sukses dibanding dirinya{/cps}"
    "{cps=35}Namun ada juga yang tidak bisa memenuhi ekspetasinya{/cps}"
    "{cps=35}Dan aku tidak mau menjadi orang gagal...{/cps}"
    mc "{cps=35}Hah...{/cps}"
    "{cps=35}Disaat aku sedang melamun memikirkan hal itu{/cps}"
    "{cps=40}BRAK!{/cps}"
    mc"{cps=40}Hue! Apa yan-{/cps}"
    "{cps=40}[t] melempar buku ke mejaku dengan cukup keras{/cps}"
    t "{cps=40}Hah.... gini ya [mc]{/cps}"
    t "{cps=40}Meskipun kamu sedang banyak pikiran...{/cps}"
    t "{cps=40}{b}MINIMAL MEMPERHATIKAN!{/b}{/cps}"
    mc "{cps=50}Baik bu...{/cps}"
    "{cps=50}Sial... {w=0.1}kenapa jadi begini...{/cps}"
    v "{cps=35}Pfffftttt{/cps}"
    "{cps=50}Terdengar suara [v] yang tertawa kecil di belakangku. Dia pasti menikmati pemandangan ini.{/cps}"

    t "{cps=40}Karena kamu sepertinya punya dunia sendiri di dalam kepala itu, coba selesaikan soal yang ada di papan.{/cps}"
    
    # Soal yang lebih manusiawi
    t "{cps=40}Jika 3x + 5 = 20, berapakah nilai dari x?{/cps}"

    "{cps=35}Aduh... kepalaku mendadak kosong. Angka-angka itu seolah menari-nari di depan mataku.{/cps}"
    if jujur:
        "{cps=35}Yuuka di depanku terlihat panik, dia mengangkat lima jarinya di bawah meja sebagai isyarat.{/cps}"
    else:
        "{cps=35}Yuuka di depanku terlihat biasa saja, dia bahkan tidak memberi isyarat apapun.{/cps}"
    "{cps=35}Aku juga melihat ke arah si kembar...{/cps}"
    "{cps=35}Mereka tidak memberi respon{/cps}"
    mc "{cps=35}Cih{/cps}"
    "{cps=40}Aku harus menjawab apa...{/cps}"
    menu:
        "5":
            $ correct_answer = True
            mc "{cps=40}Jawabannya... 5, Bu.{/cps}"
            
            "{cps=35}Ibu [t] terdiam sejenak, lalu menurunkan kacamatanya.{/cps}"
            
            t "{cps=40}Tepat. Sederhana, bukan?{/cps}"
            t "{cps=40}Ingat, dalam Aljabar, tujuan kita adalah mencari 'Nilai yang Hilang' (x) dengan cara menyeimbangkan kedua sisi.{/cps}"
            
            "{cps=35}Ibu [t] menuliskan coretan di papan dengan cepat.{/cps}"
            t "{cps=40}Jika kamu punya masalah besar (20) dan ada gangguan kecil (+5), hilangkan gangguannya dulu (20-5). Baru kemudian bagi beban sisa (15) dengan kapasitasmu (3).{/cps}"
            
            "{cps=35}Entah kenapa, penjelasan Bu [t] barusan tidak hanya terdengar seperti matematika, tapi seperti cara menghadapi hidup yang sedang berantakan ini.{/cps}"
            t "{cps=35}Sudah paham?{/cps}"
            mc "{cps=35}Sudah bu{/cps}"
            t "{cps=40}Lain kali, perhatikan penjelasan saya. Duduk dan fokus!{/cps}"
            t "{cps=35}Sekarang kembali ke tempat dudukmu{/cps}"
            mc "{cps=35}Ba-baik bu{/cps}"
            
            show yuuka_smile with dissolve
            if jujur:
                "{cps=35}Yuuka menghela napas lega dan tersenyum kecil ke arahku. Di belakang, Vina tampak sedikit kecewa karena tidak bisa menertawakanku.{/cps}"
            v "{cps=60}Cih... ternyata si Specimen Langka ini bisa berhitung juga.{/cps}"

        "15":
            $ correct_answer = False
            mc "{cps=40}Jawabannya... 15, Bu?{/cps}"
            
            "{cps=35}Seketika seisi kelas tertawa. Bahkan Vina di belakangku sampai harus menutup mulutnya agar tidak terdengar terlalu keras.{/cps}"
            t "{cps=40}Lima belas? Kamu ini sedang menghitung nilai x atau harga gorengan di kantin? Salah!{/cps}"
            t "{cps=40}Berdiri di depan sampai jam pelajaran saya selesai!{/cps}"
            
            show yuuka_sad with dissolve
            "{cps=35}Yuuka menepuk jidatnya. Dia sudah memberiku kode, tapi aku malah salah tangkap.{/cps}"

        "3":
            $ correct_answer = False
            mc "{cps=40}Jawabannya... 3?{/cps}"
            
            t "{cps=40}Salah! Ternyata lamunanmu benar-benar merusak kemampuan logikamu.{/cps}"
            t "{cps=40}Silakan berdiri di samping papan tulis sampai saya selesai menjelaskan.{/cps}"
            
            "{cps=35}Aku hanya bisa tertunduk lesu sementara beberapa siswi lain berbisik-bisik menertawakanku.{/cps}"

    "{cps=50}Kelas pun kembali dilanjutkan{/cps}"
    if correct_answer:
        "{cps=35}Untung saja tadi jawabanku benar...{/cps}"
    else:
        "{cps=35}Andai saja tadi jawabanku benar... mungkin kakiku tidak akan sepegal ini karena berdiri di depan.{/cps}"
    
    "{cps=40}Dan tidak terasa sudah waktunya istirahat.{/cps}"
    "{cps=35}Sisa pelajaran terasa seperti siksaan yang lambat. Suara kapur yang beradu dengan papan tulis terdengar seperti detak jam yang menghitung mundur keberanianku.{/cps}"
    "{cps=35}Aku melirik ke arah [y]. Punggungnya tegak, fokusnya seolah tak tergoyahkan.{/cps}"
    "{cps=35}Namun sepertinya dia masih sedikit kesal dengan pilihanku tadi.{/cps}"
    "{cps=35}Ya... mau gimana lagi. Pilihanku sudah bulat{/cps}"
    play sound "audio/sfx/school bell.mp3"
    "{cps=40}*Ting... Tong... Ting... Tong...*{/cps}"

    t "{cps=40}Cukup untuk jam ini. Pekerjaan rumah kalian adalah mengerjakan latihan halaman 45 sebagai pendalaman.{/cps}"
    t "{cps=40}[mc], pastikan kamu mencuci wajahmu, kamu terlihat sangat pucat.{/cps}"
    t "{cps=40}Kita ketemu lagi nanti setelah istirahat dengan mata pelajaran Sejarah, jadi siapkan buku kalian nanti{/cps}"

    "{cps=35}Begitu Bu [t] melangkah keluar, suasana kelas yang tadinya sunyi mendadak pecah. Suara tawa dan obrolan mulai memenuhi ruangan, tapi bagiku, suara itu terasa seperti derau statis yang jauh.{/cps}"

    # --- REAKSI YUUKA & VINA (AS BESTIES) ---
    show yuuka_neutral at left
    show vina_smile at right
    with dissolve

    "{cps=35}[y] langsung berdiri. Dia merapikan bukunya dengan gerakan cepat, seolah ingin segera menghilang dari sini. Vina, yang duduk di belakangku, langsung berpindah ke samping Yuuka, merangkul bahunya dengan akrab.{/cps}"

    if correct_answer:
        v "{cps=60}Wah, lihat Yuuka... ternyata si Specimen kita ini otaknya masih sinkron dengan dunia nyata. Aku kira dia sudah lupa cara menghitung x.{/cps}"
        
        y "{cps=40}(Menghela napas) Baguslah kalau begitu. Aku tidak perlu repot-repot mencarikan guru les untuk orang yang keras kepala.{/cps}"
        
        "{cps=35}Yuuka melirikku sejenak. Ada sedikit rasa lega di matanya, tapi dia segera membuang muka saat menyadari aku balik menatapnya.{/cps}"
    else:
        v "{cps=60}Duh, Yuuka... sepertinya kita harus memberi pahlawan kita ini kalkulator sebagai hadiah ulang tahun ke 17? Benar-benar jawaban yang 'berani'.{/cps}"
        
        y "{cps=40}Sudah kuberi kode, tapi dia malah melamun...{/cps}"
        
        "{cps=35}Yuuka menatapku dengan tatapan yang sulit diartikan—campuran antara kesal dan rasa kasihan yang mendalam. Vina hanya menyeringai puas.{/cps}"

    # --- PERSIAPAN PERGI KE KANTIN ---
    v "{cps=60}Sudahlah, Yuu. Ayo ke kantin, aku lapar sekali. Nanti jajanan favoritmu habis kalau kita terus berdiri di sini.{/cps}"
    y "{cps=35}Ah iya juga{/cps}"
    v "{cps=35}[mc], kamu mau ke kantin juga?{/cps}"
    mc "{cps=35}Sepertinya nggak dulu deh, ada kegiatan lain juga{/cps}"
    v "{cps=35}Kegiatan? Padahal kamu ga ada organisasi?{/cps}"
    mc "{cps=35}Dikira aku nggak bisa punya kegiatan apa?{/cps}"
    v "{cps=35}Ehehe, yaudah. sampai jumpa [mc]{/cps}"
    mc "{cps=35}Sampai jumpa...{/cps}"
    "{cps=35}[v] dan [y] pun ke kantin meninggalkanku{/cps}"
    mc "{cps=35}Baiklah... sudah waktunya{/cps}"
    "{cps=35}Aku pun berjalan menuju ke ruangan yang dijanjikan oleh kak [f]{/cps}"
    "{cps=35}Ditengah lorong yang aku lewati{/cps}"
    "{cps=35}Aku mencoba mengingat nama ruangan yang tadi dibahas{/cps}"
    f "{cps=35}nanti kamu ketika istirahat coba ke ruang klub sastra{/cps}"
    mc "{cps=35}Ruang klub sastra ya...{/cps}"
    mc "{cps=35}Dimana?{/cps}"
    "{cps=35}Aku tidak tahu ruangan itu berada dimana...{/cps}"
    mc "{cps=35}Hmmmm....{/cps}"
    "???" "{cps=35}Hei [mc]{/cps}"
    mc "{cps=35}Hah?{/cps}"
    "{cps=35}Aku menengok ke belakang{/cps}"
    yk "{cps=35}Kamu terlihat bingung sekali, ada apa?{/cps}"
    mc "{cps=35}Ummnn....{/cps}"
    mc "{cps=35}Gini [yk]... kamu tahu nggak ruangan klub sastra?{/cps}"
    yk "{cps=35}Tentu saja aku tahu! Aku kan anggota klub itu{/cps}"
    yk "{cps=35}Memangnya kenapa?{/cps}"
    mc "{cps=35}Aku mau kesana{/cps}"
    yk "{cps=35}Heeee.... mau ketemu Onee-san ya?{/cps}"
    mc "{cps=35}Maksudmu?{/cps}"
    yk "{cps=35}Eh? Bukan?? Lalu kamu ngapain ke sana?{/cps}"
    mc "{cps=35}Aku mau ketemu dengan kak [f]{/cps}"
    yk "{cps=35}Hmmm.... kayaknya kak [f] ada di ruang klub..{/cps}"
    yk "{cps=35}Tapi masa kamu nggak mau ketemu dengan Onee-san?{/cps}"
    mc "{cps=35}Kakakmu itu [sh] kan?{/cps}"
    yk "{cps=35}Tentu saja, masa kamu nggak tahu sih, padahal pas perkenalan aku sudah menunjukkan itu dari awal{/cps}"
    mc "{cps=35}Ya... kalau diingat memang sih{/cps}"
    yk "{cps=35}Padahal Onee-san itu benar-benar menunggumu loh, [mc]{/cps}"
    mc "{cps=35}Ngapain dia nungguin aku?{/cps}"
    yk "{cps=35}Ya... kan dia masih ingat dengan janji denganmu{/cps}"
    mc "{cps=35}Membahas itu lagi? Dibilang dia itu mungkin salah orang{/cps}"
    mc "{cps=35}Karena jujur saja aku tidak ingat dengan kejadian itu sama sekali{/cps}"
    yk "{cps=35}Hue- parah banget{/cps}"
    mc "{cps=35}Jadi? Kamu mau menunjukan jalannya?{/cps}"
    yk "{cps=35}Tentu saja! Sini, ikut aku{/cps}"
    "{cps=35}Aku pun mengikuti [yk] menuju ke ruang klub sastra{/cps}"

    scene bg_club_corridor with fade
    play music "audio/bgm/whisper good.mp3" fadein 2.0

    "{cps=35}Aku berjalan di belakang [yk]. Berbeda dengan [y] yang langkahnya selalu terburu-buru, [yk] melangkah dengan sangat ringan, seolah dia sedang menari di atas lantai koridor ini.{/cps}"

    yk "{cps=35}Nah, kita sampai!{/cps}"

    "{cps=35}[yk] berhenti di depan sebuah pintu hijau dengan papan nama kecil bertuliskan 'Klub Sastra'. Pintu ini terlihat sedikit kusam, namun memberikan kesan tenang yang kontras dengan hiruk-pikuk sekolah.{/cps}"
    yk "{cps=35}Selamat siang! Teman-teman, lihat siapa yang aku bawa!{/cps}"
    sh "{cps=35}Kamu selalu berisik ya, [yk]{/cps}"
    f "{cps=35}Memangnya siapa yang kamu bawa?{/cps}"
    "{cps=35}Sini [mc], ayo masuk{/cps}"
    mc "{cps=35}Permisi...{/cps}"
    "{cps=35}Begitu masuk, bau buku tua dan teh melati menyapa hidungku. Ruangan ini penuh dengan rak buku yang menjulang tinggi hingga ke langit-langit.{/cps}"
    f "{cps=35}Oho! Tamu kehormatan kita akhirnya datang juga, kerja bagus, [yk]{/cps}"
    sh "{cps=35}...{/cps}"
    sh "{cps=35}Ternyata orang yang kakak bilang tadi itu dia ya...{/cps}"
    f "{cps=35}Ya... begitulah{/cps}"
    f "{cps=35}Karena aku lihat tadi dia terlihat kesulitan, jadi sebagai senior yang baik ya aku coba bantu dia{/cps}"
    f "{cps=35}Kamu juga ada urusan denganya kan [sh]{/cps}"
    sh "{cps=35}Nggak begitu...{/cps}"
    "{cps=35}Shoko sedang duduk di sudut ruangan, memegang sebuah buku tebal. Dia menatapku sejenak—tatapannya masih sama, dalam dan sulit diartikan—sebelum kembali menunduk ke bukunya.{/cps}"
    f "{cps=35}Jadi, kamu kesini mau mendengar ceritanya kan?{/cps}"
    mc "{cps=35}I-iya kak!{/cps}"
    f "{cps=35}Sayang sekali!{/cps}"
    mc "{cps=35}Eh?{/cps}"
    f "{cps=35}Kamu aslinya aku ajak kesini biar kamu jadi anggota klub sastra!{/cps}"
    mc "{cps=35}HAH?{/cps}"
    mc "{cps=35}Tapi kan aku tidak mau gabung ke klub manapun kak{/cps}"
    f "{cps=35}*ckckck Nggak seperti itu konsepnya [mc]{/cps}"
    f "{cps=35}[yk], jelaskan{/cps}"
    yk "{cps=35}Ahem! Jadi begini [mc]. Klub Sastra itu bukan cuma soal baca buku atau bikin puisi yang bikin ngantuk.{/cps}"

    yk "{cps=35}Di sekolah ini, setiap murid harus terdaftar di satu 'wadah' kalau tidak mau dianggap sebagai 'titik buta' oleh sistem OSIS. Kamu tahu kan, Kak Maya itu perfeksionis?{/cps}"

    f "{cps=35}Benar. Dan rasionya sederhana: Kalau kamu tetap 'Solo', Maya akan terus mengincarmu untuk masuk OSIS sampai kamu menyerah.{/cps}"

    f "{cps=35}Tapi, kalau kamu terdaftar di sini... setidaknya kamu punya 'alibi' hukum untuk menolak dia. Kita ini semacam... zona netral.{/cps}"
    mc "{cps=40}Zona netral? Tapi tetap saja itu namanya gabung organisasi, Kak.{/cps}"

    f "{cps=35}Fufufu. Anggap saja ini 'keanggotaan pasif'. Kamu tidak perlu ikut rapat, tidak perlu ikut proker. Cukup taruh namamu di sini, dan sebagai gantinya...{/cps}"

    "{cps=35}Fumi mencondongkan tubuhnya ke depan. Tatapannya berubah menjadi sangat serius, membuatku refleks menahan napas.{/cps}"

    f "{cps=35}Aku akan menceritakan apa yang sebenarnya terjadi dari hubunganku dengan Kisaragi [sa] dan juga kasus Ikazaki [mi]. Sesuatu yang bahkan tidak tercatat di arsip resmi sekolah ini meski kamu mencarinya dimana pun.{/cps}"

    "{cps=35}Aku terdiam. Tawaran ini terlalu berisiko, tapi rasa ingin tahuku tentang Kakak seolah-olah ditarik paksa keluar.{/cps}"

    sh "{cps=35}(Tanpa menoleh dari bukunya) Jangan dipaksa, Kak. Biarkan dia memilih 'kebebasan' yang dia banggakan itu.{/cps}"

    sh "{cps=35}Meskipun kebebasan itu hanya akan membawanya pada kebingungan yang lebih dalam.{/cps}"

    mc "{cps=40}Shirohana-san...{/cps}"
    f "{cps=35}Jadi gimana [mc]? Tawaranku tidak terlalu buruk kan?{/cps}"
    mc "{cps=35}Ummnnn nggak sih kak..{/cps}"
    f "{cps=35}Jadi kamu mau bergabung?{/cps}"
    mc "{cps=35}Tidak{/cps}"
    f "{cps=35}Hah?{/cps}"
    "{cps=35}[f] terdiam beberapa saat{/cps}"
    f "{cps=35}Kamu nggak salah ngomong kan [mc]?{/cps}"
    mc "{cps=35}Nggak kok, aku memang tetap tidak mau gabung ke organisasi manapun{/cps}"
    f "{cps=35}Sumpah?{/cps}"
    f "{cps=35}Padahal aku sudah effort sejauh ini demi kamu... bahkan aku sampai mengundang [sh] ke sini...{/cps}"
    f "{cps=35}Walau dia memang anggota klub sih{/cps}"
    mc "{cps=35}Apa hubungannya?{/cps}"
    "{cps=35}[sh] Menutup bukunya dengan suara keras{/cps}"
    sh "{cps=35}Hah... sudah kubilang kan, Kak. Dia itu tipe orang yang kuat pendiriannya.{/cps}"
    "{cps=35}Shoko berdiri, menatapku dengan tatapan yang tajam, namun kali ini ada sedikit rasa... sedih?{/cps}"
    sh "{cps=35}Ikazaki-kun, aku tahu kamu itu tidak tertarik dengan organisasi manapun saat ini..{/cps}"
    sh "{cps=35}Namun, kamu harus ingat...{/cps}"
    sh "{cps=35}Jika kamu perlu apapun, kamu bisa datang ke klub ini, anggap saja ini adalah rumah kedua milikmu{/cps}"
    mc "{cps=35}Kenapa sih kalian sampai segitunya demi aku?{/cps}"
    yk "{cps=35}Kalau ditanya kenapa ya...{/cps}"
    yk "{cps=35}Kenapa ya, [sh] nee?{/cps}"
    sh "{cps=35}Seperti 10 tahun yang lalu{/cps}"
    mc "{cps=35}Apa sih... itu lagi yang dibahas..{/cps}"
    mc "{cps=35}Jujur saja ya [sh]... aku tidak terlalu ingat dengan kejadian itu, bahkan bertemu denganmu saja aku tidak ingat{/cps}"
    sh "{cps=35}Aku paham kok, namun...{/cps}"
    sh "{cps=35}Kalau kamu mau mengingat masa itu kembali, kamu bisa melihat album foto yang ada dirumahmu{/cps}"
    sh "{cps=35}Mungkin foto itu masih ada{/cps}"
    mc "{cps=35}Foto?{/cps}"
    sh "{cps=35}Sebelum aku pindah, kita sempat berfoto..{/cps}"
    sh "{cps=35}Dan seharusnya masih ada foto itu di album{/cps}"
    mc "{cps=35}Kenapa kamu seyakin itu?{/cps}"
    sh "{cps=35}Karena kita berdua yang memasangnya{/cps}"
    mc "{cps=35}Aku... tidak mengerti{/cps}"
    mc "{cps=35}Mungkin nanti ketika dirumah akan aku coba cari{/cps}"
    f "{cps=35}Heloo... aku masih ada di sini loh?{/cps}"
    mc "{cps=35}Ah aku sampai lupa kalau ada kak [f]{/cps}"
    f "{cps=35}Kamu beneran ga mau gabung ya [mc]? Akan aku beri 'servis' deh~{/cps}"
    "{cps=35}[f] terus menempel diriku agar aku mau bergabung{/cps}"
    "{cps=35}Namun maaf.. aku sudah kuat menghadapi ini{/cps}"
    mc "{cps=35}Maaf kak, sekali lagi aku bilang, aku tidak tertarik dengan organisasi, namun kalau memang aku diharuskan gabung..{/cps}"
    f "{cps=35}Kamu gabung dengan kita?{/cps}"
    mc "{cps=35}Aku akan berusaha membantu banyak organisasi tanpa harus terlibat secara langsung{/cps}"
    f "{cps=35}Dengan cara?{/cps}"
    m "{cps=35}Menjadi volunteer{/cps}"
    "{cps=35}Suara tak asing datang dari depan pintu, dengan langkah yang tegas{/cps}"
    "{cps=35}Siluet rambut hitam dengan aksen kuning yang berkilau, berdiri di depan pintu klub sastra{/cps}"
    f "{cps=35}Wah wah wah...{/cps}"
    f "{cps=35}Tak ku sangka kamu akan datang ke ruangan klub milikku{/cps}"
    f "{cps=35}[m]{/cps}"
    mc "{cps=35}Kak [m], ngapain kakak disini?{/cps}"
    m "{cps=35}Kebetulan aku sedang lewat dan mendengar pembicaraan kalian{/cps}"
    f "{cps=35}Kamu mendengarkan dari kapan?{/cps}"
    m "{cps=35}Semenjak [mc] masuk ke ruangan{/cps}"
    f "{cps=35}Bukannya itu sama aja dengan penguntit?{/cps}"
    m "{cps=35}Aku tidak menguntit kok, hanya saja aku penasaran dengan pilihan yang diambil oleh [mc]{/cps}"
    mc "{cps=35}Kenapa sih aku yang selalu jadi pusat perhatian oleh kalian?{/cps}"
    m "{cps=35}Karena seperti yang kamu tahu, [mc]{/cps}"
    m "{cps=35}Kamu adalah satu-satunya murid laki yang ada di sini{/cps}"
    m "{cps=35}Jadi kami selalu mengawasi gerak-gerikmu dan memastikan kalau kamu tidak akan melanggar norma yang berlaku di sekolah ini{/cps}"
    f "{cps=35}Mengawasi? Atau memang kamu nggak mau kehilangan penerusmu di OSIS, [m]?{/cps}"
    m "{cps=35}Pikirkan apa pun yang kamu mau, Kisaragi. Tapi yang jelas, Ikazaki [mc] sudah membuat pilihannya untuk tidak bergabung denganmu.{/cps}"
    "{cps=35}Maya melangkah masuk, aroma parfumnya yang tajam langsung mendominasi ruangan, mengalahkan bau teh melati milik klub sastra.{/cps}"
    m "{cps=35}Jadi, [mc]. Kamu bilang ingin menjadi 'Volunteer'?{/cps}"
    mc "{cps=35}Iya, Kak. Dengan begitu aku bisa membantu siapa pun tanpa harus menyakiti salah satu pihak{/cps}"
    "{cps=35}Menyakiti? memangnya siapa yang disakiti, [mc]?{/cps}"
    "{cps=35}Aku tidak begitu mengerti, tapi aku tetap ingin menjadi volunteer{/cps}"
    m "{cps=35}Menarik. Tapi volunteer pun butuh pengawasan. Bagaimana kalau kita buat kesepakatan?{/cps}"
    mc "{cps=35}Kesepakatan apa lagi?{/cps}"
    m "{cps=35}Kamu bebas tidak masuk klub mana pun. Tapi, setiap program kerja dari klub manapun atau osis, kamu harus ikut serta{/cps}"
    mc "{cps=35}Bukannya itu terlalu banyak?{/cps}"
    m "{cps=35}Kamu keberatan?{/cps}"
    mc "{cps=35}Sudah jelas kak!{/cps}"
    m "{cps=35}Kalau begitu, kamu bisa memilih{/cps}"
    f "{cps=35}Cih lembek banget kamu [m]{/cps}"
    m "{cps=35}Diam lah [f], jadi pilihanmu?{/cps}"
    mc "{cps=35}Aku memilih 2 saja, OSIS dan Sastra{/cps}"
    mc "{cps=35}Apakah itu tidak masalah?{/cps}"
    m "{cps=35}Tidak terlalu buruk, karena klub lain juga tidak sesibuk ini{/cps}"
    m "{cps=35}Aku terima, dan sebagai bayarannya...{/cps}"
    m "{cps=35}Aku akan memberimu akses ke arsip data kesiswaan jika kamu butuh mencari 'sesuatu'.{/cps}"
    "{cps=35}Aku tersentak. Akses arsip? Itu berarti aku bisa mencari data tentang Kakakku secara legal.{/cps}"
    sh "{cps=35}Jangan terlalu percaya padanya, [mc].{/cps}"
    sh "{cps=35}Sepertinya dia memiliki rencana lain...{/cps}"
    m "{cps=35}Aku tidak ada rencana lain kok{/cps}"
    m "{cps=35}Jadi jawabanmu?{/cps}"
    mc "{cps=35}Ummnn.... Kalau aku jadi volunteer apakah akan sendirian saja?{/cps}"
    m "{cps=35}Tentu saja tidak, akan aku berikan salah satu anggotaku untuk membantu?{/cps}"
    m "{cps=35}Namun kamu tidak perlu tahu siapa orangnya{/cps}"
    mc "{cps=35}Kalau begitu... aku setuju. Aku akan menjadi volunteer untuk OSIS dan Klub Sastra.{/cps}"
    m "{cps=35}Keputusan yang bijak, [mc].{/cps}"
    "{cps=35}Maya menyeringai tipis. Kemenangan kecil terpancar dari tatapannya. Dia mengeluarkan sebuah buku saku kecil bersampul perak dari sakunya dan meletakkannya di atas meja.{/cps}"
    m "{cps=35}Ini adalah buku catatan kegiatanmu. Setiap bantuan yang kamu berikan harus ditandatangani oleh penanggung jawab kegiatan.{/cps}"
    f "{cps=35}Dan jangan lupa, [mc]. 'Servis' dariku tetap berlaku kalau kamu bosan dengan aturan kaku Maya. Fufufu.{/cps}"
    sh "{cps=35}...{/cps}"
    "{cps=35}[sh] menatap buku itu dengan tatapan dingin, lalu beralih menatapku. Seolah dia ingin mengatakan sesuatu, tapi tertahan oleh kehadiran [m]{/cps}"
    play sound "audio/sfx/school bell.mp3"
    "{cps=40}*Ting... Tong... Ting... Tong...*{/cps}"

    m "{cps=35}Waktu istirahat sudah habis. Kembalilah ke kelas. Ingat, [mc], statusmu sekarang adalah 'Volunteer Terawasi'. Jangan sampai aku mendengar laporan buruk tentangmu.{/cps}"

    mc "{cps=35}Iya, Kak. Aku mengerti.{/cps}"

    "{cps=35}Aku mengambil buku itu. Rasanya lebih berat daripada kelihatannya. Aku segera berpamitan dan melangkah keluar dari ruangan yang penuh dengan aroma persaingan itu.{/cps}"
    scene bg_school_corridor with fade
    play music "audio/bgm/tiptoeing around.mp3" fadein 2.0

    "{cps=35}Aku berjalan menyusuri koridor. Pikiranku berkecamuk. Volunteer? Arsip kesiswaan? Dan siapa 'anggota' yang dimaksud Maya untuk membantuku?{/cps}"
    mc "{cps=35}Hah... sepertinya aku baru saja menukar kebebasanku dengan ini...{/cps}"
    mc "{cps=35}Tidak masalah lah, daripada nanti kehidupanku terlalu biasa{/cps}"
    "{cps=35}Aku ingin kembali ke kehidupan normalku{/cps}"
    play sound "audio/sfx/sfxbell.mp3"
    play sound "audio/sfx/walk.mp3"
    "{cps=35}*Tap. Tap. Tap.*{/cps}"
    
    "{cps=35}Langkah kaki yang tegas berhenti tepat di depanku. Aku mendongak dan melihat seorang siswi berdiri mematung di tengah jalan, menghalangi jalurku sepenuhnya.{/cps}"
    show abby_stern at center with dissolve
    "???" "{cps=40}Kamu terlambat tiga puluh detik untuk kembali ke kelas, Ikazaki [mc].{/cps}"
    "{cps=35}Kamu siapa?{/cps}"
    "???" "{cps=35}Hooo... kamu tidak tahu aku siapa?{/cps}"
    "???" "{cps=35}Padahal sudah kelihatan jelas jabatanku ini..{/cps}"
    mc "{cps=35}Sudahlah, aku tidak ada urusan denganmu.{/cps}"
    "{cps=35}HAHHH?{/cps}"
    mc "{cps=35}Mohon menepi{/cps}"
    "???" "{cps=35}Apa yan-{/cps}"
    "{cps=35}Aku memegang bahunya dan mendorongnya dengan perlahan agar dia berpindah{/cps}"
    "???" "{cps=35}Heee!?{/cps}"
    "???" "{cps=35}Dasar tidak sopan! Apa-apaan kamu ini!?{/cps}"
    mc "{cps=35}Aku tidak ada waktu untuk berbicara denganmu{/cps}"
    "???" "{cps=35}Setidaknya kamu bertanya dong namaku siapa?{/cps}"
    mc "{cps=35}Aku tadi sudah bertanya namun kamu belum menjawab{/cps}"
    mc "{cps=35}Dan aku tidak ingin kehilangan waktuku cuman demi itu{/cps}"
    "???" "{cps=35}Cih...{/cps}"
    ab "{cps=35}[ab].{/cps}"
    ab "{cps=35}Itu namaku{/cps}"
    mc "{cps=35}Oh gitu{/cps}"
    "{cps=35}Aku langsung melanjutkan langkahku ke kelas{/cps}"
    ab "{cps=35}Masa itu saja responmu!?{/cps}"
    mc "{cps=35}Aku tidak dengar~{/cps}"
    ab "{cps=35}Awas saja kamu, [mc]...{/cps}"
    ab "{cps=35}Aku tidak terima dengan penghinaan ini...{/cps}"
    scene bg_classroom with fade
    play music "audio/bgm/tiptoeing around.mp3" fadein 2.0

    "{cps=35}Aku melangkah masuk ke kelas tepat saat bel jam pelajaran Sejarah berhenti bergema. Napasku sedikit memburu, bukan karena lelah, tapi karena rasa sesak yang aneh di dadaku.{/cps}"

    "{cps=35}Aku mencoba bersikap biasa saja saat melewati meja [y]. Namun, tanpa menoleh pun, aku bisa merasakan hawa dingin yang memancar dari sana.{/cps}"

    show vina_smile at right with dissolve
    v "{cps=60}Wah, wah... lihat siapa yang baru saja kembali dari 'petualangan' di luar sana. Wajahmu terlihat seperti orang yang baru saja menantang maut, [mc].{/cps}"

    mc "{cps=35}Jangan sekarang, Vin. Aku sedang tidak ingin bercanda.{/cps}"

    "{cps=35}Aku duduk dan langsung memasukkan buku pemberian [m] ke dalam laci meja. Namun, bunyi benturan kecil buku itu dengan laci kayu seolah terdengar sangat keras di tengah kesunyian kelas.{/cps}"
    show yuuka_stern at left with dissolve
    y "{cps=40} Buku apa itu [mc]? Sepertinya aku tidak pernah melihat buku seperti itu?{/cps}"
    v "{cps=35}Aku juga tidak pernah melihatnya...{/cps}"
    v "{cps=35}Kamu maling ya?{/cps}"
    mc "{cps=35}Hei! Bukan begitu... ini bagian dari kesepakatan volunteer...{/cps}"
    v "{cps=35}Volunteer? Kamu jadi volunteer?{/cps}"
    mc "{cps=35}Yap{/cps}"
    v "{cps=35}Heee... oke kalau begitu, nanti bantuin aku nugas ya{/cps}"
    mc "{cps=35}Enak aja! nggak begitu{/cps}"
    v "{cps=35}Hei [y], kita bisa menyuruh dia nih, kamu nggak mau?{/cps}"
    y "{cps=40}Terserahlah, mending kita siapin alat tulis kita{/cps}"
    y "{cps=35}Karena [t] sudah mau masuk ke kelas{/cps}"
    v "{cps=35}Ah iya juga!{/cps}"
    "{cps=35}Mereka kembali ke tempat duduk mereka{/cps}"
    mc "{cps=35}Hah...{/cps}"
    "{cps=35}Aku kembali memandang kondisi sekitar{/cps}"
    "{cps=35}Dan tidak sengaja bertatapan dengan [sh]{/cps}"
    "{cps=35}Namun dia langsung membuang wajahnya{/cps}"
    "{cps=35}Aku gak tahu apa yang terjadi barusan...{/cps}"
    yk "{cps=35}Cieee...{/cps}"
    sh "{cps=35}Apaan sih, [yk]{/cps}"
    yk "{cps=35}Nggak ada apa-apa kok nee-san...{/cps}"
    yk "{cps=35}Hanya saja aku sedang memikirkan skenario terlucu{/cps}"
    sh "{cps=35}Simpan saja ide mu itu{/cps}"
    yk "{cps=35}Baik{/cps}"
    "{cps=35}Suasana kelas mendadak hening total. Hanya ada suara gesekan kursi yang ditarik dan bunyi detak jam dinding yang entah kenapa terdengar lebih keras dari biasanya.{/cps}"

    play sound "audio/sfx/sliding door.mp3"
    "{cps=35}*SRAAAK!*{/cps}"

    "{cps=35}Pintu depan terbuka lebar. [t] masuk dengan langkah yang sanggup membuat murid paling berisik sekalipun langsung tegak duduknya. Beliau membawa setumpuk buku yang diletakkan di meja dengan dentuman pelan.{/cps}"

    t "{cps=40}Selamat siang. Simpan semua barang yang tidak berkaitan dengan Sejarah. Sekarang.{/cps}"
    "{cps=35}Aku segera memasukkan alat tulis lain, memastikan buku pemberian Maya itu benar-benar tersembunyi jauh di dalam laci. Aku bisa merasakan tatapan Yuuka masih sesekali melirik ke arah tanganku.{/cps}"

    t "{cps=40}Hari ini kita akan membahas tentang 'Tragedi dan Pengkhianatan' dalam sejarah.{/cps}"
    "{cps=35}[t] menuliskan sebuah istilah besar di papan tulis dengan kapur yang berderit nyaring.{/cps}"

    t "{cps=40}{b}'Falsus in Uno, Falsus in Omnibus'{/b}. Ada yang tahu artinya?{/cps}"
    t "{cps=40}[mc], coba kamu jawab. Sepertinya kamu punya 'wawasan baru' setelah kejadian di lorong tadi.{/cps}"
    "{cps=35}Seketika suara kelas langsung penuh suara bisikan{/cps}"
    "{cps=35}Tentu saja yang mereka bicarakan itu aku{/cps}"
    v "{cps=35}Hue- kamu habis ngapain memangnya [mc]?{/cps}"
    mc "{cps=35}Bukan apa-apa kok...{/cps}"
    v "{cps=35}Ah masa... sepertinya mencurigakan..{/cps}"
    "{cps=35}[v] menatapku dengan wajah yang penasaran{/cps}"
    t "{cps=35}Sudah cukup!{/cps}"
    "{cps=35}Suasana kelas seketika diam{/cps}"
    t "{cps=35}Jadi, apa jawabanmu, [mc]?{/cps}"
    if correct_answer == False:
        t "{cps=35}Jangan sampai kamu salah jawab lagi seperti tadi pagi{/cps}"
    "{cps=35}Hmmmm... apa ya jawabannya{/cps}"
    "{cps=35}Aku tidak terlalu tahu bahasa latin sih.{/cps}"
    menu:
        "Satu kebohongan merusak segalanya":
            $ correct_answer_2 = True
            mc "{cps=40}Kalau tidak salah... artinya 'Satu kebohongan dalam satu hal, maka akan dianggap bohong dalam segala hal', Bu.{/cps}"
            
            t "{cps=40}Tepat sekali. Sebuah prinsip hukum lama yang menekankan pada kredibilitas individu.{/cps}"
            
            "{cps=35}Bu Nanami mengetukkan kapurnya ke papan tulis, tepat di bawah tulisan tersebut.{/cps}"

            t "{cps=40}Sekali kamu merusak kepercayaan seseorang dengan satu ketidakjujuran, maka seluruh kata-katamu setelahnya akan dipandang sebagai debu. Tidak berharga.{/cps}"

            "{cps=35}Aku merasakan hawa dingin dari arah Yuuka [y]. Dia tidak mengatakan apa-apa, tapi suara bolpoinnya yang menggores kertas terdengar sangat keras.{/cps}"

        "Kesalahan satu orang adalah kesalahan semua":
            $ correct_answer_2 = False
            mc "{cps=40}Artinya... kesalahan satu orang akan ditanggung oleh semua orang dalam kelompok itu, Bu?{/cps}"
            
            t "{cps=40}Salah. Itu pemikiran yang terlalu sempit, [mc]. Fokus kita hari ini adalah integritas pribadi.{/cps}"
            
            v "{cps=35}Duh, [mc]... sepertinya kamu benar-benar harus les bahasa asing sama aku nanti.{/cps}"
            
            t "{cps=40}Falsus in Uno, Falsus in Omnibus berarti ketidakjujuran dalam satu poin akan meruntuhkan seluruh kredibilitasmu di poin lainnya.{/cps}"

        "Aku benar-benar tidak tahu":
            $ correct_answer_2 = False
            mc "{cps=40}Maaf, Bu. Saya benar-benar tidak tahu. Bahasa Latin bukan keahlian saya.{/cps}"
            
            t "{cps=40}Setidaknya kamu jujur dengan ketidaktahuanmu. Itu lebih baik daripada berpura-pura tahu.{/cps}"
            
            t "{cps=40}Artinya adalah: Satu kebohongan akan merusak seluruh kebenaran yang kamu bangun.{/cps}"

    # --- KELANJUTAN PELAJARAN ---

    t "{cps=40}Ingatlah ini baik-baik, murid-murid. Dalam sejarah, banyak kekaisaran runtuh bukan karena musuh dari luar, tapi karena pengkhianatan kecil di dalam yang dibiarkan tumbuh.{/cps}"

    t "{cps=40}Perhatikan papan tulis. Sejarah bukan hanya tentang siapa yang menang perang, tapi tentang siapa yang 'menjual' saudaranya demi kemenangan itu.{/cps}"

    t "{cps=40}Mari kita ambil contoh klasik: {b}Marcus Junius Brutus{/b}.{/cps}"

    t "{cps=40}Brutus adalah orang paling dipercaya oleh Julius Caesar. Tapi pada Idus Maret 44 SM, dia menjadi salah satu penikam Caesar. Kenapa?{/cps}"

    v "{cps=35}Karena dia ingin jadi pahlawan, Bu?{/cps}"

    t "{cps=40}Bukan sekadar itu, Vina. Dia melakukannya atas nama 'kebaikan bersama'. Tapi sejarah mencatatnya sebagai simbol pengkhianatan tertinggi.{/cps}"

    t "{cps=40}Dante Alighieri bahkan menempatkan Brutus di lingkaran neraka terdalam, tepat di mulut iblis. Bagi Dante, tidak ada dosa yang lebih besar daripada mengkhianati orang yang mempercayaimu.{/cps}"

    "{cps=35}Aku merasa kursi yang kududuki mendadak panas. Di depanku, Yuuka [y] sedang mencoret-coret buku catatannya dengan gerakan kasar.{/cps}"

    t "{cps=40}Mari kita lihat buktinya dalam sejarah modern: {b}Kasus Benedict Arnold{/b} di Revolusi Amerika.{/cps}"

    t "{cps=40}Dia adalah jenderal hebat, tapi karena merasa tidak dihargai, dia mencoba menjual benteng West Point ke Inggris. Namanya sekarang identik dengan kata 'pengkhianat' di Amerika.{/cps}"

    t "{cps=40}Satu keputusan salah, satu rahasia yang disimpan rapat, cukup untuk menghapus ribuan jasa baik yang pernah dia lakukan sebelumnya.{/cps}"

    "{cps=35}Bu Nanami berhenti tepat di samping meja Yuuka. Yuuka langsung menunduk dalam.{/cps}"

    t "{cps=40}Apakah menurutmu kepercayaan itu seperti kaca, Yuuka?{/cps}"

    y "{cps=35}...Iya, Bu. Sekali retak, bayangannya tidak akan pernah utuh lagi.{/cps}"

    t "{cps=40}Jawaban yang filosofis. Bagus.{/cps}"

    "{cps=35}Selama dua jam berikutnya, Bu Nanami membedah berbagai kasus intelijen masa perang. Tentang bagaimana kode-kode rahasia dihancurkan karena satu orang yang 'bernyanyi' kepada musuh.{/cps}"

    "{cps=35}Aku hanya bisa menatap buku perak pemberian Maya di dalam laci. Buku itu sekarang terasa seperti bom waktu yang bisa meledak kapan saja.{/cps}"

    scene black with fade
    stop music fadeout 4.0

    "{cps=35}Dua jam yang penuh siksaan mental itu akhirnya berakhir seiring bunyi bel pulang.{/cps}"

    play sound "audio/sfx/school bell.mp3"
    "{cps=40}*Ting... Tong... Ting... Tong...*{/cps}"

    scene bg_classroom_sunset with fade
    play music "audio/bgm/evewalk.mp3" fadein 2.0

    "{cps=35}Warna oranye matahari senja menembus jendela kelas, menciptakan bayangan panjang di lantai. Suasana yang seharusnya romantis ini justru terasa sangat canggung.{/cps}"

    show vina_smile at right with dissolve
    v "{cps=35}Ugh... kepalaku mau pecah. Bu Nanami kalau ngasih contoh sejarah kok nakutin banget ya? Kayak lagi nyidang narapidana.{/cps}"

    v "{cps=35}[y], ayo ke kafe! Aku butuh asupan gula biar nggak stres.{/cps}"
    y "{cps=35}Hei.. kita kan ada audit gudang penyimpanan{/cps}"
    v "{cps=35}Ah iya juga...{/cps}"
    v "{cps=35}Arrrrhhhh aku ingin bersantai...{/cps}"
    v "{cps=35}Ah!{/cps}"
    "{cps=35}[v] menatapku{/cps}"
    v "{cps=35}Kenapa kita tidak menyuruh ini anak aja?{/cps}"
    mc "{cps=35}Kenapa aku?{/cps}"
    v "{cps=35}Kan kamu volunteer, jadi kamu yang ngerjain yak{/cps}"
    v "{cps=35}Plisss{/cps}"
    mc "{cps=35}Yaa.... aku tidak keberatan sih...{/cps}"
    mc "{cps=35}Asal ada yang mau membantu aja{/cps}"
    v "{cps=35}Kalau itu maaf, aku tidak bisa{/cps}"
    y "{cps=35}Aku bisa sih, namu-{/cps}"
    v "{cps=35}Aku ada kegiatan lain sama [y] jadi... sampai jumpa, [mc]!{/cps}"
    v "{cps=35}Untuk listnya kamu ambil di ruang osis ya!{/cps}"
    "{cps=35}Mereka langsung meninggalkanku di ruang kelas{/cps}"
    mc "{cps=35}Hah... kegiatan lain yang akan menguras tenaga{/cps}"
    mc "{cps=35}Apa boleh buat, sebagai volunteer yang baik, harus siap dengan segala kemungkinan{/cps}"
    scene bg_school_corridor_sunset with fade
    "{cps=35}Aku berjalan menuju ruang OSIS. Tanganku meraba saku, memastikan buku itu masih ada. Rasanya aneh, aku baru saja resmi jadi volunteer dan sudah diberi tugas audit.{/cps}"
    mc "{cps=35}Hmmm.... ruang OSIS... kalau tidak salah di ujung koridor ini.{/cps}"

    "{cps=35}Begitu sampai di depan ruangan itu, aku menyadari sesuatu yang janggal. Pintunya tidak tertutup rapat, menyisakan sedikit celah.{/cps}"

    mc "{cps=35}Halo? Permisi?{/cps}"

    "{cps=35}Tidak ada jawaban. Aku mendorong pintunya perlahan. Suara engsel pintu yang berderit pelan seolah memperingatiku untuk tidak masuk, tapi aku butuh daftar audit itu sekarang.{/cps}"
    play sound "audio/sfx/door.mp3"
    scene bg_council_room_interior with dissolve
    "{cps=35}Ruangan itu sunyi. Harum aroma teh melati dan kertas baru memenuhi udara. Aku melangkah mendekati meja besar di tengah ruangan, mencari tumpukan kertas yang dimaksud Vina.{/cps}"

    mc "{cps=35}Mana ya... ah, itu dia di meja belakang.{/cps}"

    "{cps=35}Aku berjalan ke arah meja di sudut ruangan. Namun, langkahku mendadak membeku saat mendengar suara kain yang bergesekan dari balik sekat lemari arsip.{/cps}"

    play sound "audio/sfx/book.mp3"
    "???" "{cps=40}Ugh... kenapa susah sekali dilepas...{/cps}"

    mc "{cps=35}Suara itu... bukannya suara kak [m]?{/cps}"

    "{cps=35}Rasa penasaran mengalahkan logikaku. Aku mengintip sedikit dari balik celah lemari. Dan di sana...{/cps}"

    "{cps=35}Bukan hanya kak [m] yang ada di sana. Ternyata ada [ab] yang sedang berlutut di belakangnya, mencoba menarik ritsleting rok Maya yang tersangkut dengan serius.{/cps}"

    ab "{cps=40}Ketua, diam sebentar. Kalau ditarik paksa, kainnya bisa robek. Kenapa sih anda ceroboh sekali?{/cps}"

    m "{cps=40}Ugh... maaf, [ab]. Aku tadi terburu-buru.{/cps}"
    ab "{cps=40}Hah... masih untung ada aku, coba aja yang dateng malah anak itu{/cps}"

    "{cps=35}Pemandangan itu... benar-benar pemandangan yang langka.{/cps}"
    "{cps=35}Seorang komandan kedisiplinan sekolah yang menjadi sangat protektif terhadap pimpinannya{/cps}"
    "{cps=35}Dan juga seorang ketua osis yang selalu terlihat tegak, dingin, dan penuh kendali, sekarang terlihat begitu... rapuh.{/cps}"
    "{cps=35}Jujur saja, pemandangan ini jauh dari kata 'disiplin'{/cps}"

    "{cps=35}Oke, [mc]. Pilihannya dua: pergi sekarang dan anggap tidak pernah terjadi, atau...{/cps}"

    menu:
        "Berusaha menyapa":
            $ maya_rel -= 5
            $ trobos = True
            "{cps=35}Sebagai pria harus berperilaku jujur, apapun yang terjadi{/cps}"
            "{cps=35}Meski akan dibenci{/cps}"
            "{cps=35}Aku kembali mengetuk lemari yang ada di depanku{/cps}"
            play sound "audio/sfx/knock door.mp3"
            mc "{cps=40}Permisi...{/cps}"
            m "{cps=35}Hm?{/cps}"
            "{cps=35}[m] terlihat sedikit bingung{/cps}"
            "{cps=35}Wajahnya langsung memerah dan seperti yang kita tahu apa yang akan terjadi selanjutnya{/cps}"
            show maya_shocked with vpunch
            m "{cps=40}KYAAAAA!!{/cps}"
            "{cps=35}Maya refleks berbalik sambil menutupi dadanya. Matanya menatapku dengan campuran antara amarah dan malu yang luar biasa.{/cps}"
            ab "{cps=40}I-IKAZAKI?! Sejak kapan kamu di sana?! Keluar! KELUAR SEKARANG!!{/cps}"
            ab "{cps=40}Beraninya kamu masuk tanpa izin dan melihat kondisi Ketua yang seperti ini! Dasar mesum!{/cps}"
            mc "{cps=40}Maaf! Aku cuma mau ambil list audit!{/cps}"
            ab "{cps=35}Cepat keluar!{/cps}"
            mc "{cps=35}Ba-baik{/cps}"
            m "{cps=35}Sial... kenapa aku sampai lupa menutup pintu..{/cps}"
            "{cps=35}Aku langsung berbalik dan menunggu kak [m] berganti pakaian di luar{/cps}"

        "Pergi secara diam-diam":
            $ trobos = False
            $ maya_rel -= 3
            "{cps=35}Aku mencoba melangkah mundur dengan sangat pelan. Tapi malangnya, kakiku menyenggol sebuah tempat sampah besi.{/cps}"
            play sound "audio/sfx/jatoh.mp3"
            "{cps=35}*PRANG!*{/cps}"
            ab "{cps=40}Siapa itu?!{/cps}"
            m "{cps=35}[ab], coba kamu cek{/cps}"
            "{cps=35}Baik!{/cps}"
            "{cps=35}[ab] langsung keluar dari balik lemari dan langsung melihatku{/cps}"
            "{cps=35}Keheningan yang sangat canggung menyelimuti ruangan selama beberapa detik.{/cps}"
            ab "{cps=40}...Kamu. Berapa banyak yang kamu lihat?{/cps}"
            mc "{cps=40}Hampir semua sih...{/cps}"
            m "{cps=35}[ab], siapa yang ada di de-{/cps}"
            m "{cps=35}Pan....{/cps}"
            "{cps=35}Wajah kak [m] langsung memerah dan seperti yang kita tahu apa yang akan terjadi selanjutnya{/cps}"
            m "{cps=35}KYAAAAAAAAAA{/cps}"
            ab "{cps=35}Ngapain kamu muncul sekarang!?{/cps}"
            ab "{cps=35}KENAPA KAMU NGGAK BILANG DARI TADI!{/cps}"
            m "{cps=35}CEPAT KAMU KELUAR!{/cps}"
            "{cps=35}Ba-baik!{/cps}"
            m "{cps=35}Sial... kenapa aku sampai lupa menutup pintu..{/cps}"
            "{cps=35}Aku langsung pergi ke luar ruangan{/cps}"

    "{cps=35}Sial... apa yang terjadi...{/cps}"
    "{cps=35}Padahal aku hanya ingin mengambil list barang..{/cps}"
    "{cps=35}Walau hal itu tidak bisa langsung aku lupakan sih...{/cps}"
    "{cps=35}Tak lama kemudian...{/cps}"
    m "{cps=35}Ahem! [mc], silahkan masuk{/cps}"
    mc "{cps=35}Ba-baik!{/cps}"
    "{cps=35}Aku langsung masuk ke ruangan itu lagi{/cps}"
    mc "{cps=35}Permisi...{/cps}"
    "{cps=35}Suasana di ruangan itu langsung berubah 180 derajat. Awalnya cukup hangat, namun sekarang menjadi dingin...{/cps}"
    "{cps=35}Bahkan lebih dingin dibandingkan kulkas. Mungkin akibat kejadian barusan.{/cps}"
    m "{cps=35}Aku harap kamu tidak mengingat semua hal yang kamu lihat barusan{/cps}"
    mc "{cps=35}Semoga aja sih begitu..{/cps}"
    "{cps=35}Walau itu sulit untuk dilupakan begitu saja{/cps}"
    ab "{cps=40}Kalau kamu tidak melupakannya, akan aku pastikan reputasimu di sekolah ini lebih buruk daripada nilai ujianmu, [mc].{/cps}"
    mc "{cps=35}Jangan mengancam diriku terus dong! Aku kan tidak sengaja.{/cps}"
    ab "{cps=40}Tidak sengaja atau tidak, kamu sudah melihat hal yang terlarang. Bahkan hampir seluruh murid di sini pun tidak pernah melihat sisi 'kurang rapi' dari Ketua.{/cps}"
    mc "{cps=35}Hah?{/cps}"
    mc "{cps=35}Padahal ini sekolah khusus perempuan?{/cps}"
    "{cps=35}Walau sekarang sudah tidak sih...{/cps}"
    ab "{cps=35}Memangnya kamu pikir ini sekolah apa hah!?{/cps}"
    "{cps=35}*bonk{/cps}"
    mc "{cps=35}Aduh!{/cps}"
    ab "{cps=40}Memangnya kamu pikir Ketua itu orang sembarangan!?{/cps}"
    "{cps=35}Setelah sekian lama, aku akhirnya mendapatkan pukulan{/cps}"
    "{cps=35}Terakhir kakakku sih{/cps}"
    m "{cps=35}Sudah cukup, [ab]. Kita punya tugas yang lebih penting.{/cps}"
    ab "{cps=35}Baik ketua...{/cps}"
    "{cps=35}Wajah [ab] seakan masih tidak puas dengan pilihan yang diambil ketua{/cps}"
    m "{cps=35}Memang sih kejadian tadi tidak bisa dihindari, ditambah kan aku lupa mengunci pintu{/cps}"
    m "{cps=35}Lokerku juga sedang rusak sih kuncinya{/cps}"
    mc "{cps=35}Memangnya rusak kenapa kak?{/cps}"
    ab "{cps=35}Kamu ini masih bertanya ya padahal sudah tau salah!{/cps}"
    "{cps=35}*bonk{/cps}"
    mc "{cps=35}Aduh!{/cps}"
    "{cps=35}Aku dipukul, lagi{/cps}"
    m "{cps=35}Cukup [ab]!{/cps}"
    ab "{cps=35}Tapi ketu-{/cps}"
    m "{cps=35}Kamu bisa melakukan itu lain kali, kan sudah aku bilang kita ada tugas yang lebih penting{/cps}"
    "{cps=35}Suara kak [m] langsung berubah, wibawanya sebagai ketua kembali muncul dan menghangatkan ruangan ini{/cps}"
    ab "{cps=35}Baik...{/cps}"
    m "{cps=35}Jadi, apa yang ingin kamu lakukan?{/cps}"
    mc "{cps=35}Begini kak, kata anak osis tadi aku disuruh melakukan audit gudang{/cps}"
    mc "{cps=35}Dan kata kakak juga aku akan ditemani seseorang{/cps}"
    m "{cps=35}Ah! Kebetulan banget{/cps}"
    m "{cps=35}Jadi orang yang aku maksud itu ada di depanmu{/cps}"
    mc "{cps=35}Depanku? Maksud kakak...{/cps}"
    "{cps=35}Aku memadang [ab] yang berusaha untuk mengelak{/cps}"
    ab "{cps=35}Ketua? Kamu tidak salah pilih kan?{/cps}"
    ab "{cps=35}Masa ketua ingin aku satu kelompok sama orang ini?{/cps}"
    mc "{cps=35}Memangnya aku juga mau denganmu?{/cps}"
    ab "{cps=35}HAH?{/cps}"
    ab "{cps=35}Aku juga ga sudi denganmu!{/cps}"
    m "{cps=35}Cukup kalian berdua!{/cps}"
    m "{cps=35}Simpan sifat kekanak-kanakan kalian{/cps}"
    m "{cps=35}Ini itu tugas yang harus penuh ketelitian{/cps}"
    m "{cps=35}Aku melihat [ab] dan kamu itu adalah orang yang teliti sekaligus bisa menyelesaikan tugas ini dengan tepat waktu{/cps}"
    mc "{cps=35}Tapi kan belum tentu bisa dipasangkan begitu saja kak{/cps}"
    mc "{cps=35}Harus ada persetujuan dari kedua belah pihak{/cps}"
    m "{cps=35}Kamu sudah menandatangani surat itu kan?{/cps}"
    mc "{cps=35}Memang sih...{/cps}"
    m "{cps=35}Kalau kamu sudah menandatangani, itu sudah cukup untuk persetujuanmu{/cps}"
    ab "{cps=35}Tapi ketua, kan aku belum menj-{/cps}"
    m "{cps=35}Ssssttttt{/cps}"
    m "{cps=35}Aku yang punya otoritas{/cps}"
    m "{cps=35}Kalau aku melihat kalian berdua bisa bekerjasama, berarti aku bisa memasangkan kalian berdua{/cps}"
    ab "{cps=35}Nggak gitu konsepnya ketua{/cps}"
    m "{cps=35}Keputusanku itu mutlak, kamu mau melawan perintahku{/cps}"
    ab "{cps=35}Selama ini aku memang selalu setuju dengan pilihanmu.. tapi untuk kali ini..{/cps}"
    ab "{cps=35}Aku menolak{/cps}"
    m "{cps=35}Padahal kamu ingin berbincang dengan anak laki?{/cps}"
    "{cps=35}Wajah [ab] langsung memerah, seakan-akan rahasia dia dibongkar langsung{/cps}"
    ab "{cps=35}A-apa maksud ketua!?{/cps}"
    ab "{cps=35}Sejak kapan aku bilang begitu!?{/cps}"
    m "{cps=35}Padahal dulu pas kamu daftar ngomongnya beg-{/cps}"
    mc "{cps=35}Aku.. tidak paham{/cps}"
    ab "{cps=35}Kamu jangan beri komentar!{/cps}"
    m "{cps=35}Sudahlah [ab], anggap saja ini sebuah latihan{/cps}"
    ab "{cps=35}Uhhm...{/cps}"
    "{cps=35}[ab] menatapku dengan tatapan yang sangat tajam, tapi kali ini ada sedikit rona merah di pipinya yang tidak bisa dia sembunyikan.{/cps}"
    m "{cps=35}Nah, [mc]. Ini daftar barang yang harus diaudit. Dan ini kunci gudang penyimpanan basement.{/cps}"
    play sound "audio/sfx/cling.mp3"
    "{cps=35}Maya menyerahkan seikat kunci berat dan sebuah buku audit kepadaku.{/cps}"
    mc "{cps=35}Hmmm.... sepertinya tidak terlalu banyak{/cps}"
    m "{cps=35}Sebaiknya kamu jangan menyepelekan sesuatu hal{/cps}"
    m "{cps=35}Bisa saja dikit namun nanti malah menyebar{/cps}"
    mc "{cps=35}Iya kak...{/cps}"
    m "{cps=35}Tapi kamu bisa kan?{/cps}"
    mc "{cps=35}Tentu saja kak{/cps}"
    m "{cps=35}Kalau ada pertanyaan bisa ditanyakan ke [ab]{/cps}"
    ab "{cps=35}Sebaiknya jangan banyak bertanya{/cps}"
    "{cps=35}Sepertinya [ab] masih belum bisa menerimaku untuk hadir di lingkungan ini{/cps}"
    m "{cps=35}Hah... sepertinya kamu harus mulai terbiasa dengan sifatnya ya, [mc]{/cps}"
    m "{cps=35}Dia memang begitu namun semakin lama pasti akan membaik kok{/cps}"
    mc "{cps=35}Baik....{/cps}"
    m "{cps=35}Kamu ada pertanyaan?{/cps}"
    mc "{cps=35}Untuk saat ini sih belum... mungkin ini kak, arah ke ruangan itu{/cps}"
    m "{cps=35}Kalau itu [ab] akan memandumu. Dan ingat...{/cps}"
    m "{cps=35}Apa yang terjadi di ruangan ini, tetap di ruangan ini. Mengerti?{/cps}"
    "{cps=35}[m] kembali memegang bahuku, tangannya yang lembut seakan-akan membuat diriku tenang{/cps}"
    mc "{cps=35}Mengerti, Kak...{/cps}"
    "{cps=35}Namun disaat yang sama...{/cps}"
    "{cps=35}Ada masalah yang harus aku hadapi{/cps}"
    "{cps=35}Aku tidak ingin bilang ini masalah... Namun...{/cps}"
    "{cps=35}Aku punya firasat buruk{/cps}"
    m "{cps=35}Sebaiknya kamu bergegas, [mc]. Karena [ab] sudah berada di depan ruangan{/cps}"
    "{cps=35}Eh? Sejak kap-{/cps}"
    ab "{cps=35}Ayo cepat jalan! Lama banget jadi orang!{/cps}"
    "{cps=35}Entah kenapa aku merasa sedang mengalami MOS{/cps}"
    mc "{cps=35}Baik...{/cps}"
    m "{cps=35}Semoga kegiatan kalian lancar{/cps}"
    "{cps=35}*Clek{/cps}"
    mc "{cps=35}Jadi, kita kemana?{/cps}"
    ab "{cps=35}Kamu gausah banyak ngomong, cukup ikuti aku{/cps}"
    scene bg_school_corridor_sunset with fade
    play music "audio/bgm/evewalk.mp3" fadein 2.0

    "{cps=35}Aku berjalan di belakang [ab]. Suara denting lonceng di lehernya terdengar setiap kali dia melangkah dengan cepat. Dia tampak sangat terburu-buru, mungkin karena malu.{/cps}"

    mc "{cps=35}Hei, jalannya pelan-pelan sedikit. Aku bawa buku ini juga.{/cps}"
    ab "{cps=35}Diam! Kamu itu lambat sekali!{/cps}"
    ab "{cps=35}Dan soal yang dikatakan Ketua tadi... jangan pernah kamu pikirkan, apalagi kamu tanyakan!{/cps}"
    mc "{cps=35}Maksudmu soal kamu yang ingin berbincang dengan laki-laki?{/cps}"
    "{cps=35}[ab] mendadak berhenti berjalan. Dia berbalik dan menatapku dengan wajah yang benar-benar merah padam.{/cps}"
    ab "{cps=35}JANGAN {w=0.1} BAHAS {w=0.1} ITU {w=0.1} LAGI{/cps}"
    ab "{cps=35}Mengerti?{/cps}"
    mc "{cps=35}U-uh...{/cps}"
    "{cps=35}Kenapa dia sampai segitunya?{/cps}"
    "{cps=35}Perjalanan kami kembali sangat sunyi, dan langkah kaki kami sangat berbeda{/cps}"
    mc "{cps=35}Anu... memangnya ada apa sih?{/cps}"
    ab "{cps=35}K-K-KAMU!{/cps}"
    ab "{cps=35}Itu cuma taktik Ketua untuk mengerjaiku! Aku sama sekali... tidak tertarik... dengan makhluk sepertimu!{/cps}"
    mc "{cps=35}Iya, iya. Aku paham. Tidak perlu sampai berteriak di lorong.{/cps}"
    "{cps=35}Aku hanya bisa menghela napas. Sepertinya audit ini akan menjadi sesi 'penyiksaan' mental bagiku.{/cps}"
    "{cps=35}Kami sampai di depan pintu besi tua menuju gudang. Udara dingin dan aroma debu mulai tercium.{/cps}"
    ab "{cps=35}Buka pintunya. Dan ingat, jangan sentuh apapun kecuali barang yang ada di daftar.{/cps}"
    mc "{cps=35}Baik...{/cps}"
    "{cps=35}Aku membuka pintunya{/cps}"
    "{cps=35}Ruangan itu penuh sekali dengan debu{/cps}"
    scene bg_storage_room_dark with fade
    play sound "audio/sfx/breathing.mp3"
    "{cps=35}*Uhuk! Uhuk!*{/cps}"
    mc "{cps=35}Debunya tebal sekali... Sepertinya tempat ini tidak pernah disentuh selama bertahun-tahun.{/cps}"
    ab "{cps=35}Tentu saja. Ini gudang arsip lama dan barang-barang yang sudah tidak terpakai.{/cps}"
    mc "{cps=35}Masa untuk sekelas sekolah khusus perempuan sampai sekotor ini?{/cps}"
    ab "{cps=35}Jangan bertanya ke aku! Aku kan hanya komandan kedisiplinan!{/cps}"
    mc "{cps=35}Disini ada tukang bersih-bersih kan?{/cps}"
    mc "{cps=35}Kenapa tidak minta tolong mereka?{/cps}"
    ab "{cps=35}Kamu ini banyak bertanya ya, [mc]...{/cps}"
    ab "{cps=35}Sebaiknya kamu menanyakan itu semua ke [m], jangan ke aku{/cps}"
    ab "{cps=35}Ditambah disini kan banyak berkas penting{/cps}"
    mc "{cps=35}Padahal kebanyakan peralatan olahraga? apa disini tidak pernah ada kegiatan olahraga?{/cps}"
    ab "{cps=35}CUKUP!{/cps}"
    ab "{cps=35}Kalau kamu bertanya sekali lagi, aku kurung kamu disini{/cps}"
    mc "{cps=35}Kalau aku dikurung di sini, kamu melapor ke kak [m] gimana?{/cps}"
    ab "{cps=35}Moh... kamu nyalain lampu dulu sana, daripada ngomong aja{/cps}"
    ab "{cps=35}Barang-barang disini tidak akan mengaudit dirinya sendiri{/cps}"
    mc "{cps=35}Memangnya mereka punya nyawa?{/cps}"
    ab "{cps=35}BERISIK!{/cps}"
    mc "{cps=35}Iya, iya. Galak amat...{/cps}"
    "{cps=35}Aku meraba-raba dinding di dekat pintu, mencari sakelar yang dimaksud.{/cps}"
    play sound "audio/sfx/lamp.mp3" # Suara sakelar agak macet
    "{cps=35}*Klik... Klik...*{/cps}"
    mc "{cps=35}Kok nggak nyala?{/cps}"
    ab "{cps=35}Tekan yang keras! Sakelarnya memang agak rewel.{/cps}"
    play sound "audio/sfx/lamp.mp3"
    # Gunakan efek flash putih singkat sebelum ganti background
    show white with flash
    scene bg_storage_room_bright with dissolve
    "{cps=35}Lampu neon di langit-langit berkedip-kedip sebentar, mengeluarkan suara mendengung yang menyakitkan telinga sebelum akhirnya menerangi seisi ruangan.{/cps}"
    mc "{cps=35}Wah...{/cps}"
    mc "{cps=35}Masih redup{/cps}"
    ab "{cps=35}Ya... mau gimana lagi... ayo [mc]{/cps}"
    ab "{cps=35}Kita audit barang disini{/cps}"
    mc "{cps=35}Hm!{/cps}"
    ab "{cps=35}Ingat ya jangan sampai kamu menyentuh barang apapun yang ada disini{/cps}"
    mc "{cps=35}Oke, oke. Aku mulai ya. Jangan kaget kalau nanti aku malah menemukan harta karun.{/cps}"
    ab "{cps=35}Jangan mimpi. Palingan cuma tikus atau kecoak. Sudah, cepat kerjakan bagianmu di rak sana!{/cps}"
    "{cps=35}Aku melangkah ke pojok kiri, ke arah tumpukan dokumen yang terlihat seperti menara miring. Jariku mulai menelusuri map-map usang yang warnanya sudah memudar.{/cps}"
    "{cps=35}Satu per satu aku mengecek daftar di buku audit. Peralatan pramuka... berkas absensi 7 tahun yang lalu.{/cps}"
    mc "{cps=35}Kenapa buku absensi masih ada disini padahal mereka sudah lulus lama?{/cps}"
    ab "{cps=35}Jangan tanya ke aku, tanya saja ke [m]{/cps}"
    mc "{cps=35}Hmmmm.... ok{/cps}"
    "{cps=35}Kami melanjutkan audit di ruangan ini{/cps}"
    "{cps=35}Sampai 15 menit kemudian...{/cps}"
    "{cps=35}Aku menemukan suatu hal yang menarik perhatianku{/cps}"
    mc "{cps=35}Apa ini?{/cps}"
    "{cps=35}Aku melihat tumpukan buku yang tergeletak di rak paling bawah{/cps}"
    "{cps=35}Buku itu seakan-akan memanggilku dengan nada hangat{/cps}"
    "{cps=35}Walau aku tahu kalau buku itu tidak bisa berbicara{/cps}"
    "{cps=35}Namun aku ingin menyentuh buku itu{/cps}"
    ab "{cps=35}Jangan kamu sentuh!{/cps}"
    mc "{cps=35}Eh?{/cps}"
    ab "{cps=35}Tugas kita disini hanya melakukan audit, tidak lebih{/cps}"
    mc "{cps=35}Tapi-{/cps}"
    ab "{cps=35}Tidak ada tapi-tapi!{/cps}"
    mc "{cps=35}Kamu aslinya juga penasaran kan?{/cps}"
    ab "{cps=35}Nggak juga kok{/cps}"
    "{cps=35}Tapi dari reaksimu sepertinya iya sih..{/cps}"
    "{cps=35}Aku menghiraukan pendapatnya dan langsung mengambil buku itu{/cps}"
    ab "{cps=35}Ja-{/cps}"
    "{cps=35}'Proposal kegiatan'{/cps}"
    mc "{cps=35}Kenapa proposal seperti itu ada disini?{/cps}"
    "{cps=35}'Ikazaki'{/cps}"
    mc "{cps=35}Loh? Kok ada namaku?{/cps}"
    ab "{cps=35}Berarti milikmu itu, [mc]{/cps}"
    mc "{cps=35}Nggak mungkin sih, kan aku baru masuk sekitar 3 hari{/cps}"
    mc "{cps=35}Lagipula aku nggak pernah masuk ke ruangan ini{/cps}"
    ab "{cps=35}Apa kamu ada kerabat yang pernah sekolah disini?{/cps}"
    mc "{cps=35}Ummm{/cps}"
    "{cps=35}Aku mencoba mengingat perkataan kak [m] terkait kakakku{/cps}"
    mc "{cps=35}Ah.... benar juga...{/cps}"
    mc "{cps=35}Kakakku pernah sekolah disini{/cps}"
    ab "{cps=35}Hah?{/cps}"
    ab "{cps=35}Yang benar?{/cps}"
    mc "{cps=35}Yap, aku tidak terlalu ingat detailnya, tapi kak [m] pernah menunjukkan fotonya{/cps}"
    ab "{cps=35}Kamu yakin itu foto kakakmu? Bukan hasil editan?{/cps}"
    mc "{cps=35}Aku ingin bilang begitu... namun dengan ditemukannya proposal ini{/cps}"
    mc "{cps=35}Sepertinya itu memang beneran{/cps}"
    ab "{cps=35}Terus kakakmu kemana?{/cps}"
    mc "{cps=35}Dia telah tiada, tepat 10 tahun yang lalu{/cps}"
    ab "{cps=35}Aku.. turut berduka cita, [mc]{/cps}"
    ab "{cps=35}Semoga beliau tenang disisinya...{/cps}"
    mc "{cps=35}Iya..{/cps}"
    "{cps=35}[ab] terdiam. Wajah galaknya sedikit melunak, berganti dengan tatapan penuh selidik ke arah buku di tanganku.{/cps}"
    ab "{cps=35}Coba buka... pelan-pelan. Kertasnya sudah sangat rapuh.{/cps}"
    play sound "audio/sfx/paper.mp3"
    "{cps=35}Aku membuka lembaran pertama dengan hati-hati. Aroma kertas tua yang khas langsung tercium, bercampur dengan bau debu ruangan.{/cps}"
    mc "{cps=35}**'Proposal Festival Budaya Gabungan - Penanggung Jawab: Ikazaki [mi]'**.{/cps}"
    mc "{cps=35}Tahunnya... 10 tahun yang lalu.{/cps}"
    ab "{cps=35}10 tahun? bukannya itu tahun dimana kakakmu tiada?{/cps}"
    mc "{cps=35}Sepertinya sih...{/cps}"
    ab "{cps=35}Bagaimana kalau ini kita bawa ke [m]{/cps}"
    mc "{cps=35}Untuk apa?{/cps}"
    ab "{cps=35}Sudah jelas bukan? Untuk melanjutkan program ini lah!{/cps}"
    ab "{cps=35}Kamu tidak ingin kakakmu memiliki penyesalan bukan?{/cps}"
    mc "{cps=35}Memang sih... tapi kan...{/cps}"
    "{cps=35}*grep{/cps}"
    "{cps=35}Aku bisa merasakan jarinya yang lembut{/cps}"
    ab "{cps=35}Tenang saja, aku akan membantumu{/cps}"
    mc "{cps=35}Kenapa... kamu mau membantuku?{/cps}"
    ab "{cps=35}Memangnya perlu alasan untuk membantu teman?{/cps}"
    "{cps=35}Wajahnya penuh dengan tekad yang kuat{/cps}"
    "{cps=35}Padahal kamu sebelumnya menjaga jarak...{/cps}"
    mc "{cps=35}Ano...{/cps}"
    ab "{cps=35}Kenapa, [mc]?{/cps}"
    mc "{cps=35}Sampai kapan kamu memegang tanganku..{/cps}"
    ab "{cps=35}Hweee!?{/cps}"
    "{cps=35}[ab] tiba-tiba menarik diri, wajahnya memerah karena sadar posisi kami tadi sangat dekat{/cps}"
    ab "{cps=35}Bukan berarti aku ingin mendekatimu loh, jangan geer!{/cps}"
    mc "{cps=35}Oke...{/cps}"
    ab "{cps=35}Baiklah, list barang yang sudah di audit masih kurang atau belum?{/cps}"
    mc "{cps=35}Seharusnya sih sudah...{/cps}"
    ab "{cps=35}Kalau belum lengkap mending kamu periksa lagi deh{/cps}"
    ab "{cps=35}Bagianku juga belum selesai...{/cps}"
    ab "{cps=35}Cih, kenapa sih bagianku selalu banyak...{/cps}"
    "{cps=35}Sepertinya dia perlu bantuan...{/cps}"
    "{cps=35}Apa perlu aku membantunya?{/cps}"
    menu:
        "Bantu Abby":
            $ apatis = False
            $ abby_rel += 10
            "{cps=35}Melihatnya menggerutu sambil mengatur tumpukan kardus sendirian, aku tidak tega juga.{/cps}"
            mc "{cps=35}Sini, biar aku bantu. Bagian atas itu terlalu tinggi untukmu, kan?{/cps}"
            ab "{cps=35}Kamu menghinaku ya?!{/cps}"
            ab "{cps=35}Padahal kamu lebih pendek dariku?{/cps}"
            mc "{cps=35}Bukan begitu. Kalau kita kerjakan berdua, kita bisa lebih cepat keluar dari gudang berdebu ini.{/cps}"
            ab "{cps=35}Ugh... ya sudah{/cps}"
            mc "{cps=35}Sisa bagian mana?{/cps}"
            ab "{cps=35}Bagian atas{/cps}"
            mc "{cps=35}Hmmm itu cukup tinggi{/cps}"
            ab "{cps=35}Oleh karena itu aku pakai tangga{/cps}"
            "{cps=35}[ab] menempatkan tangga itu tepat di depan lemari{/cps}"
            ab "{cps=35}Aku akan naik, kamu pegangin tangganya{/cps}"
            mc "{cps=35}Kenapa nggk aku aja?{/cps}"
            ab "{cps=35}Ini kan bagianku, sudah kamu tetap dibawah saja{/cps}"
            mc "{cps=35}Baik...{/cps}"
            "{cps=35}[ab] mulai menaiki anak tangga satu per satu. Tangga kayu tua itu berderit pelan, seolah memprotes beban yang diterimanya.{/cps}"
            mc "{cps=35}Hati-hati, tangganya agak goyang.{/cps}"
            ab "{cps=35}Diamlah, fokus saja pegangi tangganya! Jangan sampai matamu melirik ke mana-mana ya!{/cps}"
            "{cps=35}Aku hanya bisa menghela napas sambil mencengkeram sisi tangga dengan erat. Posisi ini... sebenarnya agak canggung.{/cps}"
            "{cps=35}Aku berdiri tepat di bawahnya, dan aroma sampo apel dari rambutnya tercium jelas saat dia bergerak mengecek barang di rak paling atas.{/cps}"
            ab "{cps=35}Ok... barang ini juga sudah....{/cps}"
            ab "{cps=35}[mc], sebelah mana lagi yang belum?{/cps}"
            mc "{cps=35}Di sebelah kananmu, [ab]{/cps}"
            ab "{cps=35}Baik{/cps}"
            "{cps=35}[ab] melanjutkan auditnya dengan serius, dia selalu menunjukkan wibawanya, entah bagaimana caranya{/cps}"
            "{cps=35}Meski telah mengalami berbagai kesulitan sejak bertemu denganku{/cps}"
            "{cps=35}Namun entah kenapa...{/cps}"
            "{cps=35}Aku merasa seperti memiliki kakak{/cps}"
            ab "{cps=35}[mc], masih ada lagi?{/cps}"
            mc "{cps=35}Eh? Sudah sih...{/cps}"
            ab "{cps=35}Yang benar? Nadamu tidak meyakinkan pun{/cps}"
            mc "{cps=35}Beneran{/cps}"
            ab "{cps=35}Ok{/cps}"
            "{cps=35}*BRAK{/cps}"
            mc "{cps=35}Aduh! Apa-apaan itu!?{/cps}"
            mc "{cps=35}Kenapa kamu melempar buku auditmu kewajahku?{/cps}"
            ab "{cps=35}Biar cepat saja sih{/cps}"
            ab "{cps=35}Sekarang kamu cepat menepi dari tempat turunku!{/cps}"
            mc "{cps=35}Baik{/cps}"
            "{cps=35}Aku langsung melepas tanganku dari tangga yang dia naiki{/cps}"
            ab "{cps=35}Hei! Jangan dilepas juga dong!{/cps}"
            mc "{cps=35}Ehehe maaf{/cps}"
            mc "{cps=35}Nah cepat turun, nanti aku lepas nih{/cps}"
            ab "{cps=35}Iya-iya...{/cps}"
            "{cps=35}*sreeet{/cps}"
            ab "{cps=35}Nah, karena bagianku sudah selesai.. sekarang apa?{/cps}"

        "Fokus pada Proposal":
            $ apatis = True
            $ abby_rel -= 2
            "{cps=35}Ah nanti aja deh{/cps}"
            "{cps=35}Toh dia sudah besar juga, ngapain aku membantunya{/cps}"
            "{cps=35}Aku juga masih sangat penasaran dengan isi proposal ini, jadi lebih baik aku membaca dan menelaah ini lebih dalam selagi dia sibuk.{/cps}"
            mc "{cps=35}Semangat ya, [ab]. Aku lagi ada urusan{/cps}"
            mc "{cps=35}Jangan panggil aku kalau ada apa-apa loh{/cps}"
            ab "{cps=35}Cih! Benar-benar tidak punya inisiatif ya...{/cps}"
            "{cps=35}[ab] terus menggerutu sambil memposisikan tangga untuk mencegek rak bagian atas{/cps}"
            "{cps=35}Sementara aku lanjut membaca proposal itu{/cps}"
            mc "{cps=35}Heee pentas seni ya...{/cps}"
            "{cps=35}*Bletak{/cps}"
            mc "{cps=35}Aduh! Kalo ngarahin tangga yang bener dong!{/cps}"
            ab "{cps=35}Ya maaf, aku kan cuma sendiri{/cps}"
            ab "{cps=35}Lagipula kamu nggak membantu{/cps}"
            mc "{cps=35}Mau gimana lagi? Aku aja sibuk{/cps}"
            "{cps=35}Situasi kembali menjadi hening{/cps}"
            "{cps=35}Aku lanjut membaca proposal itu, dan [ab] masih berusaha menempatkan tangga{/cps}"
            ab "{cps=35}Yosh, sepertinya sudah pas{/cps}"
            "Dalam hati [ab]" "{cps=35}Tapi nanti gimana kalau aku jatuh ya...{/cps}"
            ab "{cps=35}Hei, [mc]!{/cps}"
            mc "{cps=35}Apalagi?{/cps}"
            ab "{cps=35}Pegangin tangga, aku mau ngecek atas{/cps}"
            mc "{cps=35}Hah... yaudah{/cps}"
            mc "{cps=35}Nah, cepat kamu naik{/cps}"
            ab "{cps=35}Iya-iya{/cps}"
            ab "{cps=35}Jangan lihat atas loh!{/cps}"
            mc "{cps=35}Ngapain juga aku lihat atas{/cps}"
            "{cps=35}[ab] melanjutkan kegiatannya dalam melakukan audit{/cps}"
            "{cps=35}Disisi lain, aku mencoba membaca sedikit proposal yang ditulis oleh kakakku{/cps}"
            ab "{cps=35}Ok... barang ini juga sudah....{/cps}"
            ab "{cps=35}[mc], sebelah mana lagi yang belum?{/cps}"
            mc "{cps=35}Jangan tanya aku, itu kan pekerjaanmu{/cps}"
            ab "{cps=35}Masa aku harus kerja 2 kali?{/cps}"
            mc "{cps=35}Ya itu mah deritamu{/cps}"
            ab "{cps=35}Hmph, dasar{/cps}"
            "{cps=35}[ab] melakukan audit bagian atas untuk kedua kalinya{/cps}"
            "{cps=35}Wajahnya masih terlihat sedikit kesal karena aku tidak membantu banyak{/cps}"
            "{cps=35}Tapi ya mau gimana lagi, ada yang lebih penting soalnya{/cps}"
            ab "{cps=35}Sip, sudah selesai{/cps}"
            ab "{cps=35}[mc], menyingkirlah{/cps}"
            "{cps=35}Aku langsung menyingkir sesuai arahan dari [ab]{/cps}"
            "{cps=35}Dan tentu saja tanganku tetap memegang tangga itu{/cps}"
            ab "{cps=35}Nah, bagianku juga sudah selesai, sekarang apa?{/cps}"

    mc "{cps=35}Sudah sih... tinggal laporan ke kak [m]{/cps}"
    "{cps=35}[ab] kembali memperhatikan proposal itu{/cps}"
    ab "{cps=35}Kamu nggak bawa itu?{/cps}"
    "{cps=35}[ab] menunjuk ke arah proposal yang aku pegang{/cps}"
    mc "{cps=35}Ini? Tentu saja lah, kan kamu sendiri yang bilang mau membawa ini ke osis{/cps}"
    ab "{cps=35}Memangnya aku bilang begitu?{/cps}"
    mc "{cps=35}Yakali ingatanku cuman 30 menit{/cps}"
    ab "{cps=35}Ternyata ingatanmu bagus juga ya, aku salut kepadamu{/cps}"
    "{cps=35}[ab] mengelus kepalaku dengan lembut{/cps}"
    mc "{cps=35}Ngapain kamu ngelus kepala orang{/cps}"
    ab "{cps=35}Apa salahnya?{/cps}"
    mc "{cps=35}Padahal tadi kamu jaga jarak{/cps}"
    ab "{cps=35}Sudahlah, ayo kita bawa{/cps}"
    ab "{cps=35}Jangan lupa kunci ruangannya{/cps}"
    mc "{cps=35}Baik{/cps}"
    play sound "audio/sfx/door.mp3"
    "{cps=35}Aku memutar kunci gudang itu. Suara gerendel besi yang mengunci seolah menandakan berakhirnya petualangan singkat kami di dalam kegelapan yang berdebu.{/cps}"
    ab "{cps=35}Sip, ayo kita berangkat{/cps}"
    "{cps=35}Hari yang melelahkan ini sepertinya akan berakhir{/cps}"
    "{cps=35}Jujur saja, aku tidak menyangka akan seperti ini{/cps}"
    "{cps=35}Bisa bertemu dengan [ab]...{/cps}"
    "{cps=35}Meski menjengkelkan sih karena dia selalu marah{/cps}"
    "{cps=35}Tapi untuk sementara aku merasa tenang{/cps}"
    ab "{cps=35}Nah.. [mc], kamu sudah siap?{/cps}"
    mc "{cps=35}Tentu saja{/cps}"
    "{cps=35}Aku menggenggam buku proposal yang kami temukan di gudang{/cps}"
    "{cps=35}Dengan harapan bahwa aku bisa tahu apa yang terjadi sebenarnya{/cps}"
    "{cps=35}[ab] mengetuk ruang osis itu{/cps}"
    ab "{cps=35}Permisi...{/cps}"
    m "{cps=35}Silahkan masuk, aku sudah menunggu kalian{/cps}"
    ab "{cps=35}Baik{/cps}"
    m "{cps=35}Jadi... bagimana kondisi di sana, lalu hasil dari kegiatan kalian?{/cps}"
    ab "{cps=35}Kondisi ditempat itu penuh dengan debu{/cps}"
    ab "{cps=35}Namun hasilnya seperti yang bisa kamu lihat{/cps}"
    "{cps=35}Hmmmm barangnya masih pada lengkap... baguslah{/cps}"
    ab "{cps=35}Terus [mc] tadi menemukan sesuatu{/cps}"
    m "{cps=35}Heee... apa itu?{/cps}"
    "{cps=35}Aku meletakan buku proposal yang tadi ditemukan{/cps}"
    m "{cps=35}Ini...{/cps}"
    m "{cps=35}Kalian menemukannya dimana?{/cps}"
    mc "{cps=35}Dalam kardus, dan entah kenapa penuh dengan debu{/cps}"
    ab "{cps=35}Terus kenapa proposal itu tidak direalisasikan?{/cps}"
    ab "{cps=35}Mungkin kamu tahu sesuatu{/cps}"
    "{cps=35}Maya terdiam. Jemarinya yang lentik perlahan menyentuh sampul buku proposal yang kusam itu. Keheningan yang menyesakkan tiba-tiba menyelimuti ruangan.{/cps}"
    m "{cps=35}Proposal ini... sudah sangat lama sekali.{/cps}"
    "{cps=35}Maya menatap nama 'Ikazaki [mi]' di sampul itu dengan tatapan yang sulit diartikan. Ada sedikit kilatan di matanya yang tidak pernah aku lihat sebelumnya.{/cps}"
    m "{cps=35}Sudah 10 tahun ya..{/cps}"
    mc "{cps=35}10 tahun?{/cps}"
    "{cps=35}[ab] melirik ke arahku sejenak, wajahnya menunjukkan kebingungan yang sama, sebelum kembali menatap Maya dengan penuh tekad.{/cps}"
    ab "{cps=35}Ketua... Apa Anda tahu sesuatu tentang ini? Maksudku, proposal ini dibuat dengan sangat detail. Rasanya tidak masuk akal jika hanya berakhir jadi sarang debu di rak paling bawah.{/cps}"
    "{cps=35}Maya menarik napas panjang. Dia menutup buku itu dan langsung menatap kami berdua.{/cps}"
    m "{cps=35}Sepuluh tahun yang lalu, sekolah ini tidak senyaman sekarang. Aturannya jauh lebih ketat, dan... ada hal-hal yang tidak boleh dipertanyakan.{/cps}"
    mc "{cps=35}Termasuk alasan kenapa proposal kakakku ditolak?{/cps}"
    m "{cps=35}Bukan ditolak sih... lebih tepatnya ada kejadian yang membuat proposal ini tidak direalisasikan{/cps}"
    ab "{cps=35}Apa kamu tahu?{/cps}"
    m "{cps=35}Kalau pun aku menceritakan ke kalian juga, kalian belum tentu mengerti{/cps}"
    ab "{cps=35}Tidak apa-apa, selagi kami tahu apa yang terjadi pada kakaknya [mc]{/cps}"
    mc "{cps=35}Kenapa kamu sampai sebegitunya demi kakakku?{/cps}"
    ab "{cps=35}Karena kenangan itu penting kan?{/cps}"
    ab "{cps=35}Jadi cepat kamu beritahu kami, [m]{/cps}"
    m "{cps=35}Hah.... pada akhirnya pasti aku akan menceritakan ini{/cps}"
    m "{cps=35}Kejadiannya tepat pada tanggal yang sama dengan hari ini{/cps}"
    m "{cps=35}Namun terjadi pada 10 tahun yang lalu{/cps}"
    m "{cps=35}Waktu dimana kakakmu masih menjabat menjadi ketua{/cps}"
    m "{cps=35}Dia adalah panutan bagi seluruh murid disini{/cps}"
    m "{cps=35}Seorang ketua... sekaligus diva di mata semua murid{/cps}"
    m "{cps=35}Termasuk para guru{/cps}"
    m "{cps=35}Aku pun juga mengagumi kakakmu, karena kakakku juga sekolah disini di waktu yang sama{/cps}"
    m "{cps=35}Dan karena kakakku dan kakakmu adalah anggota osis{/cps}"
    m "{cps=35}Jadi mereka sering berkumpul bersama{/cps}"
    m "{cps=35}Aku juga kadang-kadang memperhatikan mereka{/cps}"
    m "{cps=35}Dan aku sempat mendengar mereka membahas proposal acara{/cps}"
    "Kakaknya [m]" "{cps=35}Hmmmm.... untuk acara tahun ini kita perlu ngadain apa ya [mi]?{/cps}"
    "Kakaknya [m]" "{cps=35}Kamu ada ide?{/cps}"
    mi "{cps=35}Apa ya...{/cps}"
    mi "{cps=35}Ah! Bagaimana kalau 'Festival Live Konser'?{/cps}"
    "Kakaknya [m]" "{cps=35}Ngapain itu?{/cps}"
    mi "{cps=35}Jadi kita bisa bekerja sama dengan anak sastra{/cps}"
    mi "{cps=35}Ditambah kan nanti siapa tahu bisa menjadi terkenal{/cps}"
    "Kakaknya [m]" "{cps=35}Bekerja sama dengan anak sastra? Kedengarannya ambisius sekali, [mi]. Kamu tahu kan mereka itu sekumpulan orang yang sulit ditebak?{/cps}"
    mi "{cps=35}Justru itu serunya! Bayangkan, bait-bait puisi yang mereka tulis dengan penuh perasaan, kita ubah menjadi melodi gitar yang menghentak.{/cps}"
    mi "{cps=35}Aku ingin sekolah ini bukan hanya tempat belajar rumus, tapi tempat di mana setiap murid punya 'suara' untuk didengar.{/cps}"
    "Kakaknya [m]" "{cps=35}Kamu memang selalu idealis. Tapi... konser seperti apa yang ingin kamu bawakan?{/cps}"
    mi "{cps=35}Konser yang jujur. Konser yang menunjukkan jati diri kita yang sebenarnya{/cps}"
    mi "{cps=35}Aku akan menyebutnya... 'Kitaimirai'.{/cps}"
    "Kakaknya [m]" "{cps=35}Hah?{/cps}"
    "Kakaknya [m]" "{cps=35}Apa itu?{/cps}"
    mi "{cps=35}Ya... sesuai kepanjangannya{/cps}"
    mi "{cps=35}'Harapan Untuk Masa Depan'{/cps}"
    mi "{cps=35}Dan aku ingin kalau para penerus kita bisa untuk melanjutkan proyek ini..{/cps}"
    "Kakaknya [m]" "{cps=35}Heh... seperti yang diharapkan dari ketua{/cps}"
    mi "{cps=35}Kamu mau meneruskannya kan dik?{/cps}"
    m "{cps=35}E-eh? aku kak??{/cps}"
    mi "{cps=35}Yap, karena kemungkinan waktu aku menjabat tidak akan cukup untuk menjalankan proker ini{/cps}"
    "Kakaknya [m]" "{cps=35}Tapi kan belum tentu dia mau [mi]{/cps}"
    mi "{cps=35}Ya.. kamu ajak aja ke sekolah kita, pastikan dia sekolah di sekolah kita{/cps}"
    "Kakaknya [m]" "{cps=35}Kamu ini... egois ada batasnya tahu{/cps}"
    mi "{cps=35}Ehehe{/cps}"
    m "{cps=35}A-aku akan berusaha!{/cps}"
    mi "{cps=35}Gitu dong, tapi tenang saja, adikku juga akan kusuruh sekolah di tempat kita{/cps}"
    "Kakaknya [m]" "{cps=35}Tunggu... bukannya sekolah kita khusus perempuan?{/cps}"
    mi "{cps=35}Ya pasti akan ada waktunya sekolah akan membuka pikirannya{/cps}"
    mi "{cps=35}Dan saat itu tiba, aku ingin adikku berdiri di sini, melanjutkan apa yang kita mulai hari ini.{/cps}"
    "Kakaknya [m]" "{cps=35}Kamu benar-benar visioner yang keras kepala, [mi]. Baiklah, aku akan mendukungmu. Tapi ingat, tantangan dari pihak sekolah kita tidak akan mudah loh.{/cps}"
    mi "{cps=35}Aman kalau itumah{/cps}"
    "{cps=35}Wajah [mi] memandang ke kakakku dengan penuh harapan{/cps}"
    scene bg_council_room_sunset with dissolve
    play music "audio/bgm/tiptoeing around.mp3" fadein 2.0
    "{cps=35}Maya-senpai mengakhiri ceritanya. Keheningan di ruang OSIS terasa jauh lebih berat dari sebelumnya. Cahaya senja yang masuk lewat jendela seolah-olah menjadi saksi bisu kenangan itu.{/cps}"
    m "{cps=40}Namun... prediksi kakakmu benar sekaligus salah.{/cps}"
    mc "{cps=40}Apa maksudmu, Senpai? Sekolah ini akhirnya memang menerima laki-laki, kan?{/cps}"
    m "{cps=40}Ya. Tapi kakakmu tidak pernah melihat hari itu tiba.{/cps}"
    m "{cps=40}Tepat seminggu setelah proposal ini diajukan, kakakmu... {w=0.5}dia pergi membawa semua harapan itu bersamanya.{/cps}"
    m "{cps=40}Akibat kejadian itu, konser 'Kitaimirai' bukan hanya dibatalkan, tapi dihentikan selamanya.{/cps}"
    m "{cps=40}Kakakku yang seharusnya melanjutkan peninggalan kakakmu keburu lulus sebelum menjalankan proker ini{/cps}"
    ab "{cps=40}Jadi... itu alasan kenapa proposal ini disembunyikan?{/cps}"
    m "{cps=40}Benar. Dan alasan aku belum menceritakan itu semua... adalah karena aku takut.{/cps}"
    m "{cps=40}Aku takut jika kamu mencoba menghidupkan 'Kitaimirai', kamu akan berakhir sama seperti dia, [mc].{/cps}"
    ab "{cps=35}Tapi kan itu kejadian 10 tahun yang lalu, sekarang sudah berbeda era{/cps}"
    ab "{cps=35}Pasti kita bisa mewujudkannya{/cps}"
    ab "{cps=35}Kamu berpikir hal yang sama kan, [mc]?{/cps}"
    mc "{cps=35}U-uh....{/cps}"
    ab "{cps=35}Kenapa dari nada bicaramu seakan tidak yakin?{/cps}"
    ab "{cps=35}Padahal kamu sudah mengetahui kebenarannya sampai saat ini{/cps}"
    mc "{cps=35}Aku... perlu mencerna semua informasi ini..{/cps}"
    mc "{cps=35}Apakah aku boleh keluar sebentar kak?{/cps}"
    m "{cps=35}Silahkan{/cps}"
    "{cps=35}Aku langsung meninggalkan ruang osis itu{/cps}"
    "{cps=35}Dengan banyak informasi yang aku terima{/cps}"
    "{cps=35}Serta kenyataan bahwa kakakku meninggalkan program yang belum dijalankan{/cps}"
    mc "{cps=35}Andai aku ada otoritas...{/cps}"
    "{cps=35}Entah kenapa aku merasa kalau tidak gabung ke organisasi merupakan pilihan yang sedikit keliru{/cps}"
    "{cps=35}Karena aku tidak memiliki wewenang untuk proker ini{/cps}"
    mc "{cps=35}Cih...{/cps}"
    "{cps=35}Kenapa sih...{/cps}"
    "???" "{cps=35}Kamu nggak apa-apa?{/cps}"
    "{cps=35}Seseorang memanggilku{/cps}"
    "{cps=35}Aku tidak bisa memandang wajahnya{/cps}"
    "{cps=35}Jiwaku sudah terlalu lelah untuk ini semua...{/cps}"
    "???" "{cps=35}Ooi...{/cps}"
    mc "{cps=35}Hmmm..?{/cps}"
    "{cps=35}Aku mendongak pelan.{/cps}"
    "{cps=35}Di depanku berdiri seorang murid perempuan yang bersandar santai di tembok.{/cps}"
    "{cps=35}Wajahnya terlihat tenang, seolah beban dunia yang baru saja aku dengar hanyalah dongeng pengantar tidur baginya.{/cps}"
    "???" "{cps=35}Kamu lemas banget, memangnya ada apa?{/cps}"
    mc "{cps=35}Kamu.... siapa?{/cps}"
    ry "{cps=35}Habuki [ry]. Kelas 2-A.{/cps}"
    mc "{cps=35}Habuki....[ry]?{/cps}"
    ry "{cps=35}Yap{/cps}"
    mc "{cps=35}Kenapa kamu kesini?{/cps}"
    "{cps=35}[ry] melipat tangannya, menatapku dengan sorot mata yang sulit dibaca. Tidak ada rasa kasihan di sana, hanya ketenangan yang ganjil.{/cps}"
    ry "{cps=35}Biasanya jam segini di koridor ini sudah sepi. Tapi aku melihatmu duduk disini{/cps}"
    ry "{cps=35}Jadi daripada kamu tidak ada teman, mending aku temani{/cps}"
    mc "{cps=35}Aku... tidak apa-apa...{/cps}"
    ry "{cps=35}Wajahmu itu tidak bisa berbohong loh{/cps}"
    mc "{cps=35}Itu bukan urusanmu kan?{/cps}"
    ry "{cps=35}Memang sih, tapi kan tetap saja kamu itu perlu seorang pendengar{/cps}"
    mc "{cps=35}Pendengar ya...{/cps}"
    mc "{cps=35}Aku masih ada pendengar kok, namun hanya saja..{/cps}"
    ry "{cps=35}Hanya?{/cps}"
    mc "{cps=35}Aku membuatnya sedikit kecewa{/cps}"
    ry "{cps=35}Membuatnya kecewa, ya?{/cps}"

    "{cps=35}[ry] ikut duduk di lantai koridor, tidak jauh dariku. Gerakannya sangat santai, seolah lantai yang dingin itu adalah sofa yang empuk.{/cps}"

    ry "{cps=35}Kadang orang merasa kecewa bukan karena apa yang kamu lakukan, tapi karena mereka peduli pada apa yang sedang kamu hadapi.{/cps}"

    mc "{cps=35}Dia sudah bertekad untuk membantuku mewujudkan mimpi yang bahkan aku sendiri tidak tahu bisa kulakukan atau tidak.{/cps}"
    ry "{cps=35}Gini ya... kamu kelas 1 kan?{/cps}"
    mc "{cps=35}Iya{/cps}"
    ry "{cps=35}Selagi kamu masih kelas 1, wajar jika kamu masih bimbang{/cps}"
    ry "{cps=35}Namun ingat, usahakan untuk tidak mengecewakan orang lain{/cps}"
    ry "{cps=35}Kalau kamu mau membahas terkait masalahmu yang lain atau terkait ini, kamu bisa mencariku di loteng ketika istirahat{/cps}"
    ry "{cps=35}Namun itu untuk lain hari{/cps}"
    ry "{cps=35}Sampai jumpa{/cps}"
    "{cps=35}Dia bangkit berdiri dan mulai melangkah menjauh. Suara langkah kakinya yang pelan perlahan menghilang di ujung koridor yang gelap.{/cps}"
    mc "{cps=35}Loteng saat istirahat, ya...{/cps}"
    "{cps=35}Oh iya!{/cps}"
    "{cps=35}Aku lupa untuk perkenalan...{/cps}"
    "{cps=35}Tapi lain kali saja deh, kan aku juga besok akan ke loteng{/cps}"
    ab "{cps=35}Hayo! kamu habis ngapain!?{/cps}"
    mc "{cps=35}Hue!? A-[ab]!?{/cps}"
    mc "{cps=35}Sejak kapan kamu disini!?{/cps}"
    ab "{cps=35}Baru keluar dari ruangan sih...{/cps}"
    ab "{cps=35}Kamu kenapa tadi keluar tiba-tiba?{/cps}"
    mc "{cps=35}Umn.... entahlah{/cps}"
    mc "{cps=35}Aku tadi keluar karena belum tahu tujuanku yang sebenarnya{/cps}"
    mc "{cps=35}Namun sekarang aku sudah membulatkan tekad{/cps}"
    mc "{cps=35}Dengan mewujudkan impian kakak{/cps}"
    ab "{cps=35}Nah, gitu dong!{/cps}"
    ab "{cps=35}Jangan kayak gitu lagi ya, [mc]{/cps}"
    ab "{cps=35}Sekarang ayo kembali ke ruang osis, [m] masih menunggumu{/cps}"
    mc "{cps=35}Iya{/cps}"
    ab "{cps=35}Tapi serius ya, [mc]. Kalau kamu butuh waktu buat mikir lagi nanti, bilang saja. Jangan langsung kabur begitu.{/cps}"
    ab "{cps=35}Ketua tadi sampai terlihat sedikit... cemas.{/cps}"
    mc "{cps=35}Maaf. Aku janji tidak akan begitu lagi.{/cps}"
    scene bg_council_room_sunset with dissolve
    play music "audio/bgm/emptyroom.mp3" fadein 1.0
    "{cps=35}Begitu pintu terbuka, aku melihat kak [m] masih duduk di posisi yang sama. Dia menatapku, dan kali ini senyumnya terasa lebih tulus, seolah dia sudah tahu apa jawabanku.{/cps}"
    m "{cps=35}Sudah merasa lebih baik, [mc]?{/cps}"
    mc "{cps=35}Sudah, Kak. Maaf tadi aku tiba-tiba keluar.{/cps}"
    m "{cps=35}Jadi... keputusanmu?{/cps}"
    mc "{cps=35}Aku sudah memutuskan. Aku ingin menghidupkan kembali 'Kitaimirai'.{/cps}"
    m "{cps=35}Keputusan yang berani. Tapi seperti yang kubilang, kamu tidak punya otoritas di sini. Dan [ab]... dia punya tugas lain.{/cps}"
    m "{cps=35}Mungkin bisa saja kamu tetap menjalankan ini{/cps}"
    mc "{cps=35}Caranya gimana kak?{/cps}"
    m "{cps=35}Ajak klub sastra{/cps}"
    mc "{cps=35}Sas...tra?{/cps}"
    m "{cps=35}Karena kan kakakmu yang punya ide untuk mengajak mereka, namun seperti yang kamu tahu{/cps}"
    m "{cps=35}Jadi aku minta kamu besok bicara dengan anak dari klub sastra, entah ketua atau anggota{/cps}"
    m "{cps=35}Itu terserah padamu{/cps}"
    "{cps=35}Klub sastra ya...{/cps}"
    "{cps=35}Aku masih sedikit trauma dengan ajakan yang dilakukan secara tiba-tiba oleh kak [f]{/cps}"
    mc "{cps=35}Aku besok akan coba ajak bicara salah satu anggotanya kak{/cps}"
    m "{cps=35}Baiklah, [ab].{/cps}"
    ab "{cps=35}Iya ketua{/cps}"
    m "{cps=35}Kamu temani dia besok, karena kemungkinan besar dia akan diajak masuk sastra lagi{/cps}"
    ab "{cps=35}Kenapa saya ketua? saya kan juga mengurus kedisiplinan siswi disini{/cps}"
    ab "{cps=35}Ga mungkin saya juga ikut mengurus [mc]{/cps}"
    m "{cps=35}Tidak masalah, untuk itu aku sudah mengaturnya{/cps}"
    m "{cps=35}Kamu tidak keberatan kan?{/cps}"
    ab "{cps=35}Tidak sih...{/cps}"
    m "{cps=35}Baiklah, aku anggap setuju{/cps}"
    m "{cps=35}Aku harap kalian berdua bisa bekerja sama kembali dan bisa melancarkan kegiatan ini{/cps}"
    "[mc] & [ab]" "{cps=35}Baik{/cps}"
    "{cps=35}Dengan ini... aku sudah memiliki tujuan{/cps}"
    "{cps=35}Aku tidak akan mengulangi kesalahan yang sama denganmu, kak{/cps}"
    m "{cps=35}Baiklah, pertemuan hari ini cukup sampai di sini. Hari sudah semakin gelap, sebaiknya kalian segera pulang.{/cps}"
    m "{cps=35}Aku tunggu kabar baiknya{/cps}"
    "[mc] & [ab]" "{cps=35}Baik{/cps}"
    "{cps=35}*ceklek{/cps}"
    ab "{cps=35}Besok... jam istirahat pertama, temui aku di depan ruang klub sastra. Jangan telat, atau aku akan menyeretmu ke ruang kedisiplinan.{/cps}"
    mc "{cps=35}Iya, iya. Galak sekali.{/cps}"
    ab "{cps=35}Aku serius! Mengingat pengalamanmu dengan klub itu rasanya... mereka sangat intimidatif{/cps}"
    mc "{cps=35}Iya... tenang saja, [ab]{/cps}"
    mc "{cps=35}Aku tidak akan jatuh ke lubang yang sama kok{/cps}"
    ab "{cps=35}Baiklah kalau begitu.... sampai jumpa{/cps}"
    "{cps=35}[ab] langsung meninggalkanku{/cps}"
    "{cps=35}Namun...{/cps}"
    "{cps=35}dia berhenti sejenak, kemudian berbalik dan menatapku dengan ekspresi yang lebih tenang.{/cps}"
    ab "{cps=35}Tapi... aku senang kamu memutuskan untuk lanjut. Terima kasih sudah tidak menyerah, [mc].{/cps}"
    mc "{cps=35}E-eh? Iya...{/cps}"
    "{cps=35}Dia langsung berjalan mendahuluiku dengan langkah cepat, mungkin untuk menutupi rasa malunya.{/cps}"
    scene bg_school_gate_night with fade 
    play music "audio/bgm/gohome.mp3" fadein 2.0
    "{cps=35}Angin malam berhembus pelan saat aku melangkah keluar dari gerbang sekolah. Suasana sangat sunyi, hanya terdengar suara langkah kakiku.{/cps}"
    "{cps=35}Dari kejauhan terlihat ada yang menunggu diriku{/cps}"
    "{cps=35}Dan sepertinya dia terlihat kesal{/cps}"
    y "{cps=35}Kamu ini... kenapa sampai malam?{/cps}"
    y "{cps=35}Aku kan nungguin kamu daritadi{/cps}"
    mc "{cps=35}Perasaan aku nggak minta untuk tungguin aku deh, [y]{/cps}"
    y "{cps=35}Memang apa salahnya? {/cps}"
    y "{cps=35}Sebagai teman yang baik, aku kan khawatir kamu kenapa-kenapa{/cps}"
    mc "{cps=35}Yang ada aku yang khawatir denganmu{/cps}"
    mc "{cps=35}Sampai-sampai nungguin aku{/cps}"
    mc "{cps=35}Orang tua mu dirumah nyariin nanti{/cps}"
    y "{cps=35}Mereka sedang ada acara diluar kota{/cps}"
    y "{cps=35}Kemungkinan mereka pulang pada akhir semester{/cps}"
    mc "{cps=35}Acara apa sampai selama itu?{/cps}"
    y "{cps=35}Entahlah, aku tidak dijelaskan secara rinci oleh mereka...{/cps}"
    mc "{cps=35}Hee....{/cps}"
    mc "{cps=35}Berarti kamu sendirian di rumah selama itu?{/cps}"
    y "{cps=35}Ya begitulah...{/cps}"
    mc "{cps=35}Terus apa untungnya kamu cerita ke aku?{/cps}"
    y "{cps=35}Ya... nggak ada untungnya sih....{/cps}"
    y "{cps=35}Tapi kan aku cuman cerita{/cps}"
    y "{cps=35}Kenapa sih kamu jadi dingin akhir-akhir ini..{/cps}"
    mc "{cps=35}Nggak juga kok, lagipula kan aku sudah membantumu{/cps}"
    y "{cps=35}Iya sih...{/cps}"
    mc "{cps=35}Yaudah, ayo kita pulang, [y]{/cps}"
    y "{cps=35}Hmm!{/cps}"

    "{cps=35}Kami pun pulang bersama. Tentu saja, hanya dengan berjalan kaki.{/cps}"

    "{cps=35}Lampu jalan yang kekuningan membiaskan bayangan kami yang memanjang di atas trotoar. Suara langkah kaki kami yang beradu dengan kesunyian malam menjadi satu-satunya melodi yang menemani perjalanan ini.{/cps}"

    "{cps=35}[y] sempat terdiam cukup lama, mungkin dia masih memikirkan kata-kataku tadi. Namun, dasarnya dia memang tidak bisa diam, dia akhirnya mulai bertanya soal apa yang terjadi di ruang OSIS.{/cps}"

    "{cps=35}Aku menceritakan sedikit... tentang gudang itu, dan berkas kakakku yang berdebu.{/cps}"

    y "{cps=35}Heee... ada berkas kakakmu disana ya...{/cps}"
    mc "{cps=35}Ya... begitulah.{/cps}"

    "{cps=35}Aku tidak menceritakan soal 'Kitaimirai'. Belum saatnya. Rasanya beban itu terlalu berat jika harus dibagi dengan [y] yang selalu ceria.{/cps}"

    y "{cps=35}Tenang saja [mc], nanti kalau kamu perlu bantuan tinggal beritahu aku ya! Aku kan ahli dalam urusan... hmmm... menghiburmu!{/cps}"

    "{cps=35}Dia tertawa kecil, mencoba mencairkan suasana dingin yang tadi sempat aku buat.{/cps}"

    y "{cps=35}Sampai jumpa besok, [mc]!{/cps}"
    y "{cps=35}Oh iya! Jangan begadang loh! Kalau kamu telat besok, aku nggak mau kasih contekan PR lagi!{/cps}"

    mc "{cps=35}Iya iya, bawel.{/cps}"

    "{cps=35}[y] melambaikan tangannya dengan semangat sebelum akhirnya menghilang di balik gerbang rumahnya.{/cps}"

    "{cps=35}Aku berdiri sejenak di depan pagar rumahku sendiri. Udara malam yang dingin mulai menembus seragamku.{/cps}"

    mc "{cps=35}Akhirnya hari yang panjang ini berakhir...{/cps}"

    "{cps=35}Aku meraba tas selempangku. Di sana, proposal kusam itu masih tersimpan rapi. Sebuah beban masa lalu yang sekarang menjadi tujuanku.{/cps}"

    mc "{cps=35}Semoga besok... aku bisa memberikan jawaban yang lebih baik.{/cps}"

    stop music fadeout 2.0
    scene black with fade
    jump chapter_2_end